"""
complimentary_library_populate.py - Data definitions script

Contains all embedded data extracted from complimentary_library.db
Contains all 170 function records with parameter data
Contains helper functions for data processing
"""

from datetime import datetime
from typing import List, Tuple, Optional

# Function data structure: (id, function_id, function_name, step_variant, description, object_chain, 
# method_name, full_call, return_type, object_type, created_timestamp)
FUNCTIONS_DATA = [
    (1, 'initialize_catia_app', 'Catia on Function', 1, 'PyCATIA function for catia on function', '', 'catia', 'catia()', "<class 'pycatia.in_interfaces.application.Application'>", 'function', '2025-10-09 13:07:26'),
    (2, 'initialize_catia_app', 'Start Workbench on Application', 1, 'PyCATIA function for start_workbench on Application', 'caa', 'start_workbench', "caa.start_workbench('GenerativeShapeDesignWorkbench')", 'None', 'Application', '2025-10-09 13:07:26'),
    (3, 'initialize_catia_app', 'Create Documents', 1, 'PyCATIA function for add on Documents', 'documents', 'add', "documents.add('Part')", "<class 'pycatia.in_interfaces.document.Document'>", 'Documents', '2025-10-09 13:07:26'),
    (4, 'setup_hybrid_shape_environment', 'Create Hybridbodies', 1, 'PyCATIA function for add on HybridBodies', 'hybrid_bodies', 'add', 'hybrid_bodies.add()', "<class 'pycatia.mec_mod_interfaces.hybrid_body.HybridBody'>", 'HybridBodies', '2025-10-09 13:07:26'),
    (5, 'define_reference_axes', 'Create Direction By Coord', 1, 'PyCATIA function for add_new_direction_by_coord on HybridShapeFactory', 'hybrid_shape_factory', 'add_new_direction_by_coord', 'hybrid_shape_factory.add_new_direction_by_coord(1, 0, 0)', "<class 'pycatia.hybrid_shape_interfaces.hybrid_shape_direction.HybridShapeDirection'>", 'HybridShapeFactory', '2025-10-09 13:07:26'),
    (6, 'define_reference_axes', 'Create Direction By Coord', 2, 'PyCATIA function for add_new_direction_by_coord on HybridShapeFactory', 'hybrid_shape_factory', 'add_new_direction_by_coord', 'hybrid_shape_factory.add_new_direction_by_coord(0, 1, 0)', "<class 'pycatia.hybrid_shape_interfaces.hybrid_shape_direction.HybridShapeDirection'>", 'HybridShapeFactory', '2025-10-09 13:07:26'),
    (7, 'define_reference_axes', 'Create Direction By Coord', 3, 'PyCATIA function for add_new_direction_by_coord on HybridShapeFactory', 'hybrid_shape_factory', 'add_new_direction_by_coord', 'hybrid_shape_factory.add_new_direction_by_coord(0, 0, 1)', "<class 'pycatia.hybrid_shape_interfaces.hybrid_shape_direction.HybridShapeDirection'>", 'HybridShapeFactory', '2025-10-09 13:07:26'),
    (8, 'define_reference_axes', "Append Hybrid Shape on <Class 'Pycatia.Mec Mod Interfaces.Hybrid Body.Hybridbody'>", 1, "PyCATIA function for append_hybrid_shape on <class 'pycatia.mec_mod_interfaces.hybrid_body.HybridBody'>", 'geom_set', 'append_hybrid_shape', 'geom_set.append_hybrid_shape(x_axis)', 'None', "<class 'pycatia.mec_mod_interfaces.hybrid_body.HybridBody'>", '2025-10-09 13:07:26'),
    (9, 'define_reference_axes', "Append Hybrid Shape on <Class 'Pycatia.Mec Mod Interfaces.Hybrid Body.Hybridbody'>", 2, "PyCATIA function for append_hybrid_shape on <class 'pycatia.mec_mod_interfaces.hybrid_body.HybridBody'>", 'geom_set', 'append_hybrid_shape', 'geom_set.append_hybrid_shape(y_axis)', 'None', "<class 'pycatia.mec_mod_interfaces.hybrid_body.HybridBody'>", '2025-10-09 13:07:26'),
    (10, 'define_reference_axes', "Append Hybrid Shape on <Class 'Pycatia.Mec Mod Interfaces.Hybrid Body.Hybridbody'>", 3, "PyCATIA function for append_hybrid_shape on <class 'pycatia.mec_mod_interfaces.hybrid_body.HybridBody'>", 'geom_set', 'append_hybrid_shape', 'geom_set.append_hybrid_shape(z_axis)', 'None', "<class 'pycatia.mec_mod_interfaces.hybrid_body.HybridBody'>", '2025-10-09 13:07:26'),
    (11, 'define_reference_axes', 'Update Part', 1, 'PyCATIA function for update on Part', 'part', 'update', 'part.update()', 'None', 'Part', '2025-10-09 13:07:26'),
    (12, 'create_construction_plane', 'Create Plane Offset', 1, 'PyCATIA function for add_new_plane_offset on HybridShapeFactory', 'hybrid_shape_factory', 'add_new_plane_offset', 'hybrid_shape_factory.add_new_plane_offset(zx_plane, 500.0, False)', "<class 'pycatia.hybrid_shape_interfaces.hybrid_shape_plane_offset.HybridShapePlaneOffset'>", 'HybridShapeFactory', '2025-10-09 13:07:26'),
    (13, 'create_construction_plane', "Append Hybrid Shape on <Class 'Pycatia.Mec Mod Interfaces.Hybrid Body.Hybridbody'>", 1, "PyCATIA function for append_hybrid_shape on <class 'pycatia.mec_mod_interfaces.hybrid_body.HybridBody'>", 'geom_set', 'append_hybrid_shape', 'geom_set.append_hybrid_shape(plane1)', 'None', "<class 'pycatia.mec_mod_interfaces.hybrid_body.HybridBody'>", '2025-10-09 13:07:26'),
    (14, 'create_construction_plane', 'Update Part', 1, 'PyCATIA function for update on Part', 'part', 'update', 'part.update()', 'None', 'Part', '2025-10-09 13:07:26'),
    (15, 'create_root_point', 'Create Point On Plane', 1, 'PyCATIA function for add_new_point_on_plane on HybridShapeFactory', 'hybrid_shape_factory', 'add_new_point_on_plane', 'hybrid_shape_factory.add_new_point_on_plane(plane1, -250.0, 0.0)', "<class 'pycatia.hybrid_shape_interfaces.hybrid_shape_point_on_plane.HybridShapePointOnPlane'>", 'HybridShapeFactory', '2025-10-09 13:07:26'),
    (16, 'create_root_point', "Append Hybrid Shape on <Class 'Pycatia.Mec Mod Interfaces.Hybrid Body.Hybridbody'>", 1, "PyCATIA function for append_hybrid_shape on <class 'pycatia.mec_mod_interfaces.hybrid_body.HybridBody'>", 'geom_set', 'append_hybrid_shape', 'geom_set.append_hybrid_shape(point1)', 'None', "<class 'pycatia.mec_mod_interfaces.hybrid_body.HybridBody'>", '2025-10-09 13:07:26'),
    (17, 'create_root_point', 'Update Part', 1, 'PyCATIA function for update on Part', 'part', 'update', 'part.update()', 'None', 'Part', '2025-10-09 13:07:26'),
    (18, 'create_tip_point', 'Create Direction', 1, 'PyCATIA function for add_new_direction on HybridShapeFactory', 'hybrid_shape_factory', 'add_new_direction', 'hybrid_shape_factory.add_new_direction(yz_plane)', "<class 'pycatia.hybrid_shape_interfaces.hybrid_shape_direction.HybridShapeDirection'>", 'HybridShapeFactory', '2025-10-09 13:07:26'),
    (19, 'create_tip_point', 'Create Point On Surface With Reference', 1, 'PyCATIA function for add_new_point_on_surface_with_reference on HybridShapeFactory', 'hybrid_shape_factory', 'add_new_point_on_surface_with_reference', 'hybrid_shape_factory.add_new_point_on_surface_with_reference(plane1, point1, yz_direction, 300.0)', "<class 'pycatia.hybrid_shape_interfaces.hybrid_shape_point_on_surface.HybridShapePointOnSurface'>", 'HybridShapeFactory', '2025-10-09 13:07:26'),
    (20, 'create_tip_point', "Append Hybrid Shape on <Class 'Pycatia.Mec Mod Interfaces.Hybrid Body.Hybridbody'>", 1, "PyCATIA function for append_hybrid_shape on <class 'pycatia.mec_mod_interfaces.hybrid_body.HybridBody'>", 'geom_set', 'append_hybrid_shape', 'geom_set.append_hybrid_shape(point2)', 'None', "<class 'pycatia.mec_mod_interfaces.hybrid_body.HybridBody'>", '2025-10-09 13:07:26'),
    (21, 'create_tip_point', 'Update Part', 1, 'PyCATIA function for update on Part', 'part', 'update', 'part.update()', 'None', 'Part', '2025-10-09 13:07:26'),
    (22, 'create_spline_curve_pattern1', 'Create Reference From Object on Part', 1, 'PyCATIA function for create_reference_from_object on Part', 'part', 'create_reference_from_object', 'part.create_reference_from_object(point1)', 'object', 'Part', '2025-10-09 13:07:26'),
    (23, 'create_spline_curve_pattern1', 'Create Reference From Object on Part', 2, 'PyCATIA function for create_reference_from_object on Part', 'part', 'create_reference_from_object', 'part.create_reference_from_object(z_axis)', 'object', 'Part', '2025-10-09 13:07:26'),
    (24, 'create_spline_curve_pattern1', 'Create Spline', 1, 'PyCATIA function for add_new_spline on HybridShapeFactory', 'hybrid_shape_factory', 'add_new_spline', 'hybrid_shape_factory.add_new_spline()', "<class 'pycatia.hybrid_shape_interfaces.hybrid_shape_spline.HybridShapeSpline'>", 'HybridShapeFactory', '2025-10-09 13:07:26'),
    (25, 'create_spline_curve_pattern1', "Add Point With Constraint From Curve on <Class 'Pycatia.Hybrid Shape Interfaces.Hybrid Shape Spline.Hybridshapespline'>", 1, "PyCATIA function for add_point_with_constraint_from_curve on <class 'pycatia.hybrid_shape_interfaces.hybrid_shape_spline.HybridShapeSpline'>", 'spline1', 'add_point_with_constraint_from_curve', 'spline1.add_point_with_constraint_from_curve(ref_point1, ref_z_axis, 0.5, 1, 1)', 'None', "<class 'pycatia.hybrid_shape_interfaces.hybrid_shape_spline.HybridShapeSpline'>", '2025-10-09 13:07:26'),
    (26, 'create_spline_curve_pattern1', "Add Point on <Class 'Pycatia.Hybrid Shape Interfaces.Hybrid Shape Spline.Hybridshapespline'>", 1, "PyCATIA function for add_point on <class 'pycatia.hybrid_shape_interfaces.hybrid_shape_spline.HybridShapeSpline'>", 'spline1', 'add_point', 'spline1.add_point(point2)', 'None', "<class 'pycatia.hybrid_shape_interfaces.hybrid_shape_spline.HybridShapeSpline'>", '2025-10-09 13:07:26'),
    (27, 'create_spline_curve_pattern1', "Append Hybrid Shape on <Class 'Pycatia.Mec Mod Interfaces.Hybrid Body.Hybridbody'>", 1, "PyCATIA function for append_hybrid_shape on <class 'pycatia.mec_mod_interfaces.hybrid_body.HybridBody'>", 'geom_set', 'append_hybrid_shape', 'geom_set.append_hybrid_shape(spline1)', 'None', "<class 'pycatia.mec_mod_interfaces.hybrid_body.HybridBody'>", '2025-10-09 13:07:26'),
    (28, 'create_spline_curve_pattern1', 'Update Part', 1, 'PyCATIA function for update on Part', 'part', 'update', 'part.update()', 'None', 'Part', '2025-10-09 13:07:26'),
    (29, 'create_spline_curve_pattern2', 'Create Reference From Object on Part', 1, 'PyCATIA function for create_reference_from_object on Part', 'part', 'create_reference_from_object', 'part.create_reference_from_object(point1)', 'object', 'Part', '2025-10-09 13:07:26'),
    (30, 'create_spline_curve_pattern2', 'Create Reference From Object on Part', 2, 'PyCATIA function for create_reference_from_object on Part', 'part', 'create_reference_from_object', 'part.create_reference_from_object(point2)', 'object', 'Part', '2025-10-09 13:07:26'),
    (31, 'create_spline_curve_pattern2', 'Create Reference From Object on Part', 3, 'PyCATIA function for create_reference_from_object on Part', 'part', 'create_reference_from_object', 'part.create_reference_from_object(z_axis)', 'object', 'Part', '2025-10-09 13:07:26'),
    (32, 'create_spline_curve_pattern2', 'Create Spline', 1, 'PyCATIA function for add_new_spline on HybridShapeFactory', 'hybrid_shape_factory', 'add_new_spline', 'hybrid_shape_factory.add_new_spline()', "<class 'pycatia.hybrid_shape_interfaces.hybrid_shape_spline.HybridShapeSpline'>", 'HybridShapeFactory', '2025-10-09 13:07:26'),
    (33, 'create_spline_curve_pattern2', "Add Point on <Class 'Pycatia.Hybrid Shape Interfaces.Hybrid Shape Spline.Hybridshapespline'>", 1, "PyCATIA function for add_point on <class 'pycatia.hybrid_shape_interfaces.hybrid_shape_spline.HybridShapeSpline'>", 'spline2', 'add_point', 'spline2.add_point(ref_point2)', 'None', "<class 'pycatia.hybrid_shape_interfaces.hybrid_shape_spline.HybridShapeSpline'>", '2025-10-09 13:07:26'),
    (34, 'create_spline_curve_pattern2', "Add Point With Constraint From Curve on <Class 'Pycatia.Hybrid Shape Interfaces.Hybrid Shape Spline.Hybridshapespline'>", 1, "PyCATIA function for add_point_with_constraint_from_curve on <class 'pycatia.hybrid_shape_interfaces.hybrid_shape_spline.HybridShapeSpline'>", 'spline2', 'add_point_with_constraint_from_curve', 'spline2.add_point_with_constraint_from_curve(ref_point1, ref_z_axis, 0.3, 0, 1)', 'None', "<class 'pycatia.hybrid_shape_interfaces.hybrid_shape_spline.HybridShapeSpline'>", '2025-10-09 13:07:26'),
    (35, 'create_spline_curve_pattern2', "Append Hybrid Shape on <Class 'Pycatia.Mec Mod Interfaces.Hybrid Body.Hybridbody'>", 1, "PyCATIA function for append_hybrid_shape on <class 'pycatia.mec_mod_interfaces.hybrid_body.HybridBody'>", 'geom_set', 'append_hybrid_shape', 'geom_set.append_hybrid_shape(spline2)', 'None', "<class 'pycatia.mec_mod_interfaces.hybrid_body.HybridBody'>", '2025-10-09 13:07:26'),
    (36, 'create_spline_curve_pattern2', 'Update Part', 1, 'PyCATIA function for update on Part', 'part', 'update', 'part.update()', 'None', 'Part', '2025-10-09 13:07:26'),
    (37, 'create_reference_line', 'Create Direction', 1, 'PyCATIA function for add_new_direction on HybridShapeFactory', 'hybrid_shape_factory', 'add_new_direction', 'hybrid_shape_factory.add_new_direction(plane1)', "<class 'pycatia.hybrid_shape_interfaces.hybrid_shape_direction.HybridShapeDirection'>", 'HybridShapeFactory', '2025-10-09 13:07:26'),
    (38, 'create_reference_line', 'Create Line Pt Dir', 1, 'PyCATIA function for add_new_line_pt_dir on HybridShapeFactory', 'hybrid_shape_factory', 'add_new_line_pt_dir', 'hybrid_shape_factory.add_new_line_pt_dir(point1, dir_plane1, 0.0, 20.0, False)', "<class 'pycatia.hybrid_shape_interfaces.hybrid_shape_line_pt_dir.HybridShapeLinePtDir'>", 'HybridShapeFactory', '2025-10-09 13:07:26'),
    (39, 'create_reference_line', "Append Hybrid Shape on <Class 'Pycatia.Mec Mod Interfaces.Hybrid Body.Hybridbody'>", 1, "PyCATIA function for append_hybrid_shape on <class 'pycatia.mec_mod_interfaces.hybrid_body.HybridBody'>", 'geom_set', 'append_hybrid_shape', 'geom_set.append_hybrid_shape(line1)', 'None', "<class 'pycatia.mec_mod_interfaces.hybrid_body.HybridBody'>", '2025-10-09 13:07:26'),
    (40, 'create_reference_line', 'Update Part', 1, 'PyCATIA function for update on Part', 'part', 'update', 'part.update()', 'None', 'Part', '2025-10-09 13:07:26'),
    (41, 'create_angled_line', 'Create Reference From Object on Part', 1, 'PyCATIA function for create_reference_from_object on Part', 'part', 'create_reference_from_object', 'part.create_reference_from_object(xy_plane)', 'object', 'Part', '2025-10-09 13:07:26'),
    (42, 'create_angled_line', 'Create Reference From Object on Part', 2, 'PyCATIA function for create_reference_from_object on Part', 'part', 'create_reference_from_object', 'part.create_reference_from_object(line1)', 'object', 'Part', '2025-10-09 13:07:26'),
    (43, 'create_angled_line', 'Create Line Angle', 1, 'PyCATIA function for add_new_line_angle on HybridShapeFactory', 'hybrid_shape_factory', 'add_new_line_angle', 'hybrid_shape_factory.add_new_line_angle(ref_line1, ref_xy_plane, point1, False, 0.0, 20.0, -30.0, False)', "<class 'pycatia.hybrid_shape_interfaces.hybrid_shape_line_angle.HybridShapeLineAngle'>", 'HybridShapeFactory', '2025-10-09 13:07:26'),
    (44, 'create_angled_line', "Append Hybrid Shape on <Class 'Pycatia.Mec Mod Interfaces.Hybrid Body.Hybridbody'>", 1, "PyCATIA function for append_hybrid_shape on <class 'pycatia.mec_mod_interfaces.hybrid_body.HybridBody'>", 'geom_set', 'append_hybrid_shape', 'geom_set.append_hybrid_shape(line2)', 'None', "<class 'pycatia.mec_mod_interfaces.hybrid_body.HybridBody'>", '2025-10-09 13:07:26'),
    (45, 'create_angled_line', 'Update Part', 1, 'PyCATIA function for update on Part', 'part', 'update', 'part.update()', 'None', 'Part', '2025-10-09 13:07:26'),
    (46, 'create_extrude_surface', 'Create Direction', 1, 'PyCATIA function for add_new_direction on HybridShapeFactory', 'hybrid_shape_factory', 'add_new_direction', 'hybrid_shape_factory.add_new_direction(line2)', "<class 'pycatia.hybrid_shape_interfaces.hybrid_shape_direction.HybridShapeDirection'>", 'HybridShapeFactory', '2025-10-09 13:07:26'),
    (47, 'create_extrude_surface', 'Create Extrude', 1, 'PyCATIA function for add_new_extrude on HybridShapeFactory', 'hybrid_shape_factory', 'add_new_extrude', 'hybrid_shape_factory.add_new_extrude(spline1, 500.0, 0.0, dir_line2)', "<class 'pycatia.hybrid_shape_interfaces.hybrid_shape_extrude.HybridShapeExtrude'>", 'HybridShapeFactory', '2025-10-09 13:07:26'),
    (48, 'create_extrude_surface', "Append Hybrid Shape on <Class 'Pycatia.Mec Mod Interfaces.Hybrid Body.Hybridbody'>", 1, "PyCATIA function for append_hybrid_shape on <class 'pycatia.mec_mod_interfaces.hybrid_body.HybridBody'>", 'geom_set', 'append_hybrid_shape', 'geom_set.append_hybrid_shape(extrude1)', 'None', "<class 'pycatia.mec_mod_interfaces.hybrid_body.HybridBody'>", '2025-10-09 13:07:26'),
    (49, 'create_extrude_surface', 'Update Part', 1, 'PyCATIA function for update on Part', 'part', 'update', 'part.update()', 'None', 'Part', '2025-10-09 13:07:26'),
    (50, 'create_extrude_surface', 'Create Direction', 2, 'PyCATIA function for add_new_direction on HybridShapeFactory', 'hybrid_shape_factory', 'add_new_direction', 'hybrid_shape_factory.add_new_direction(line2)', "<class 'pycatia.hybrid_shape_interfaces.hybrid_shape_direction.HybridShapeDirection'>", 'HybridShapeFactory', '2025-10-09 13:07:26'),
    (51, 'create_extrude_surface', 'Create Extrude', 2, 'PyCATIA function for add_new_extrude on HybridShapeFactory', 'hybrid_shape_factory', 'add_new_extrude', 'hybrid_shape_factory.add_new_extrude(spline2, 500.0, 0.0, dir_line2)', "<class 'pycatia.hybrid_shape_interfaces.hybrid_shape_extrude.HybridShapeExtrude'>", 'HybridShapeFactory', '2025-10-09 13:07:26'),
    (52, 'create_extrude_surface', "Append Hybrid Shape on <Class 'Pycatia.Mec Mod Interfaces.Hybrid Body.Hybridbody'>", 2, "PyCATIA function for append_hybrid_shape on <class 'pycatia.mec_mod_interfaces.hybrid_body.HybridBody'>", 'geom_set', 'append_hybrid_shape', 'geom_set.append_hybrid_shape(extrude2)', 'None', "<class 'pycatia.mec_mod_interfaces.hybrid_body.HybridBody'>", '2025-10-09 13:07:26'),
    (53, 'create_extrude_surface', 'Update Part', 2, 'PyCATIA function for update on Part', 'part', 'update', 'part.update()', 'None', 'Part', '2025-10-09 13:07:26'),
    (54, 'create_point_geometry', 'Create Point Coord', 1, 'PyCATIA function for add_new_point_coord on HybridShapeFactory', 'hybrid_shape_factory', 'add_new_point_coord', 'hybrid_shape_factory.add_new_point_coord(-300, 0.0, 0.0)', "<class 'pycatia.hybrid_shape_interfaces.hybrid_shape_point_coord.HybridShapePointCoord'>", 'HybridShapeFactory', '2025-10-09 13:07:26'),
    (55, 'create_point_geometry', "Append Hybrid Shape on <Class 'Pycatia.Mec Mod Interfaces.Hybrid Body.Hybridbody'>", 1, "PyCATIA function for append_hybrid_shape on <class 'pycatia.mec_mod_interfaces.hybrid_body.HybridBody'>", 'geom_set', 'append_hybrid_shape', 'geom_set.append_hybrid_shape(point3)', 'None', "<class 'pycatia.mec_mod_interfaces.hybrid_body.HybridBody'>", '2025-10-09 13:07:26'),
    (56, 'create_point_geometry', 'Update Part', 1, 'PyCATIA function for update on Part', 'part', 'update', 'part.update()', 'None', 'Part', '2025-10-09 13:07:26'),
    (57, 'create_point_geometry', 'Create Point Coord', 2, 'PyCATIA function for add_new_point_coord on HybridShapeFactory', 'hybrid_shape_factory', 'add_new_point_coord', 'hybrid_shape_factory.add_new_point_coord(1000, 0.0, 0.0)', "<class 'pycatia.hybrid_shape_interfaces.hybrid_shape_point_coord.HybridShapePointCoord'>", 'HybridShapeFactory', '2025-10-09 13:07:26'),
    (58, 'create_point_geometry', "Append Hybrid Shape on <Class 'Pycatia.Mec Mod Interfaces.Hybrid Body.Hybridbody'>", 2, "PyCATIA function for append_hybrid_shape on <class 'pycatia.mec_mod_interfaces.hybrid_body.HybridBody'>", 'geom_set', 'append_hybrid_shape', 'geom_set.append_hybrid_shape(point4)', 'None', "<class 'pycatia.mec_mod_interfaces.hybrid_body.HybridBody'>", '2025-10-09 13:07:26'),
    (59, 'create_point_geometry', 'Update Part', 2, 'PyCATIA function for update on Part', 'part', 'update', 'part.update()', 'None', 'Part', '2025-10-09 13:07:26'),
    (60, 'create_spline_curve_pattern1', 'Create Reference From Object on Part', 3, 'PyCATIA function for create_reference_from_object on Part', 'part', 'create_reference_from_object', 'part.create_reference_from_object(point3)', 'object', 'Part', '2025-10-09 13:07:26'),
    (61, 'create_spline_curve_pattern1', 'Create Reference From Object on Part', 4, 'PyCATIA function for create_reference_from_object on Part', 'part', 'create_reference_from_object', 'part.create_reference_from_object(z_axis)', 'object', 'Part', '2025-10-09 13:07:26'),
    (62, 'create_spline_curve_pattern1', 'Create Spline', 2, 'PyCATIA function for add_new_spline on HybridShapeFactory', 'hybrid_shape_factory', 'add_new_spline', 'hybrid_shape_factory.add_new_spline()', "<class 'pycatia.hybrid_shape_interfaces.hybrid_shape_spline.HybridShapeSpline'>", 'HybridShapeFactory', '2025-10-09 13:07:26'),
    (63, 'create_spline_curve_pattern1', "Add Point With Constraint From Curve on <Class 'Pycatia.Hybrid Shape Interfaces.Hybrid Shape Spline.Hybridshapespline'>", 2, "PyCATIA function for add_point_with_constraint_from_curve on <class 'pycatia.hybrid_shape_interfaces.hybrid_shape_spline.HybridShapeSpline'>", 'spline3', 'add_point_with_constraint_from_curve', 'spline3.add_point_with_constraint_from_curve(ref_point3, ref_z_axis, 0.5, 0, 1)', 'None', "<class 'pycatia.hybrid_shape_interfaces.hybrid_shape_spline.HybridShapeSpline'>", '2025-10-09 13:07:26'),
    (64, 'create_spline_curve_pattern1', "Add Point on <Class 'Pycatia.Hybrid Shape Interfaces.Hybrid Shape Spline.Hybridshapespline'>", 2, "PyCATIA function for add_point on <class 'pycatia.hybrid_shape_interfaces.hybrid_shape_spline.HybridShapeSpline'>", 'spline3', 'add_point', 'spline3.add_point(point4)', 'None', "<class 'pycatia.hybrid_shape_interfaces.hybrid_shape_spline.HybridShapeSpline'>", '2025-10-09 13:07:26'),
    (65, 'create_spline_curve_pattern1', "Append Hybrid Shape on <Class 'Pycatia.Mec Mod Interfaces.Hybrid Body.Hybridbody'>", 2, "PyCATIA function for append_hybrid_shape on <class 'pycatia.mec_mod_interfaces.hybrid_body.HybridBody'>", 'geom_set', 'append_hybrid_shape', 'geom_set.append_hybrid_shape(spline3)', 'None', "<class 'pycatia.mec_mod_interfaces.hybrid_body.HybridBody'>", '2025-10-09 13:07:26'),
    (66, 'create_spline_curve_pattern1', 'Update Part', 2, 'PyCATIA function for update on Part', 'part', 'update', 'part.update()', 'None', 'Part', '2025-10-09 13:07:26'),
    (67, 'create_spline_curve_pattern2', 'Create Reference From Object on Part', 4, 'PyCATIA function for create_reference_from_object on Part', 'part', 'create_reference_from_object', 'part.create_reference_from_object(point3)', 'object', 'Part', '2025-10-09 13:07:26'),
    (68, 'create_spline_curve_pattern2', 'Create Reference From Object on Part', 5, 'PyCATIA function for create_reference_from_object on Part', 'part', 'create_reference_from_object', 'part.create_reference_from_object(point4)', 'object', 'Part', '2025-10-09 13:07:26'),
    (69, 'create_spline_curve_pattern2', 'Create Reference From Object on Part', 6, 'PyCATIA function for create_reference_from_object on Part', 'part', 'create_reference_from_object', 'part.create_reference_from_object(z_axis)', 'object', 'Part', '2025-10-09 13:07:26'),
    (70, 'create_spline_curve_pattern2', 'Create Spline', 2, 'PyCATIA function for add_new_spline on HybridShapeFactory', 'hybrid_shape_factory', 'add_new_spline', 'hybrid_shape_factory.add_new_spline()', "<class 'pycatia.hybrid_shape_interfaces.hybrid_shape_spline.HybridShapeSpline'>", 'HybridShapeFactory', '2025-10-09 13:07:26'),
    (71, 'create_spline_curve_pattern2', "Add Point on <Class 'Pycatia.Hybrid Shape Interfaces.Hybrid Shape Spline.Hybridshapespline'>", 2, "PyCATIA function for add_point on <class 'pycatia.hybrid_shape_interfaces.hybrid_shape_spline.HybridShapeSpline'>", 'spline4', 'add_point', 'spline4.add_point(ref_point4)', 'None', "<class 'pycatia.hybrid_shape_interfaces.hybrid_shape_spline.HybridShapeSpline'>", '2025-10-09 13:07:26'),
    (72, 'create_spline_curve_pattern2', "Add Point With Constraint From Curve on <Class 'Pycatia.Hybrid Shape Interfaces.Hybrid Shape Spline.Hybridshapespline'>", 2, "PyCATIA function for add_point_with_constraint_from_curve on <class 'pycatia.hybrid_shape_interfaces.hybrid_shape_spline.HybridShapeSpline'>", 'spline4', 'add_point_with_constraint_from_curve', 'spline4.add_point_with_constraint_from_curve(ref_point3, ref_z_axis, 0.3, 0, 1)', 'None', "<class 'pycatia.hybrid_shape_interfaces.hybrid_shape_spline.HybridShapeSpline'>", '2025-10-09 13:07:26'),
    (73, 'create_spline_curve_pattern2', "Append Hybrid Shape on <Class 'Pycatia.Mec Mod Interfaces.Hybrid Body.Hybridbody'>", 2, "PyCATIA function for append_hybrid_shape on <class 'pycatia.mec_mod_interfaces.hybrid_body.HybridBody'>", 'geom_set', 'append_hybrid_shape', 'geom_set.append_hybrid_shape(spline4)', 'None', "<class 'pycatia.mec_mod_interfaces.hybrid_body.HybridBody'>", '2025-10-09 13:07:26'),
    (74, 'create_spline_curve_pattern2', 'Update Part', 2, 'PyCATIA function for update on Part', 'part', 'update', 'part.update()', 'None', 'Part', '2025-10-09 13:07:26'),
    (75, 'create_guide_spline5', 'Create Reference From Object on Part', 1, 'PyCATIA function for create_reference_from_object on Part', 'part', 'create_reference_from_object', 'part.create_reference_from_object(point3)', 'object', 'Part', '2025-10-09 13:07:26'),
    (76, 'create_guide_spline5', 'Create Reference From Object on Part', 2, 'PyCATIA function for create_reference_from_object on Part', 'part', 'create_reference_from_object', 'part.create_reference_from_object(y_axis)', 'object', 'Part', '2025-10-09 13:07:26'),
    (77, 'create_guide_spline5', 'Create Spline', 1, 'PyCATIA function for add_new_spline on HybridShapeFactory', 'hybrid_shape_factory', 'add_new_spline', 'hybrid_shape_factory.add_new_spline()', "<class 'pycatia.hybrid_shape_interfaces.hybrid_shape_spline.HybridShapeSpline'>", 'HybridShapeFactory', '2025-10-09 13:07:26'),
    (78, 'create_guide_spline5', "Add Point With Constraint From Curve on <Class 'Pycatia.Hybrid Shape Interfaces.Hybrid Shape Spline.Hybridshapespline'>", 1, "PyCATIA function for add_point_with_constraint_from_curve on <class 'pycatia.hybrid_shape_interfaces.hybrid_shape_spline.HybridShapeSpline'>", 'spline5', 'add_point_with_constraint_from_curve', 'spline5.add_point_with_constraint_from_curve(ref_point3, ref_y_axis, 1, 0, 1)', 'None', "<class 'pycatia.hybrid_shape_interfaces.hybrid_shape_spline.HybridShapeSpline'>", '2025-10-09 13:07:26'),
    (79, 'create_guide_spline5', "Add Point With Constraint From Curve on <Class 'Pycatia.Hybrid Shape Interfaces.Hybrid Shape Spline.Hybridshapespline'>", 2, "PyCATIA function for add_point_with_constraint_from_curve on <class 'pycatia.hybrid_shape_interfaces.hybrid_shape_spline.HybridShapeSpline'>", 'spline5', 'add_point_with_constraint_from_curve', 'spline5.add_point_with_constraint_from_curve(point1, line2, 1, 0, 1)', 'None', "<class 'pycatia.hybrid_shape_interfaces.hybrid_shape_spline.HybridShapeSpline'>", '2025-10-09 13:07:26'),
    (80, 'create_guide_spline5', "Append Hybrid Shape on <Class 'Pycatia.Mec Mod Interfaces.Hybrid Body.Hybridbody'>", 1, "PyCATIA function for append_hybrid_shape on <class 'pycatia.mec_mod_interfaces.hybrid_body.HybridBody'>", 'geom_set', 'append_hybrid_shape', 'geom_set.append_hybrid_shape(spline5)', 'None', "<class 'pycatia.mec_mod_interfaces.hybrid_body.HybridBody'>", '2025-10-09 13:07:26'),
    (81, 'create_guide_spline5', 'Update Part', 1, 'PyCATIA function for update on Part', 'part', 'update', 'part.update()', 'None', 'Part', '2025-10-09 13:07:26'),
    (82, 'create_guide_spline6', 'Create Reference From Object on Part', 1, 'PyCATIA function for create_reference_from_object on Part', 'part', 'create_reference_from_object', 'part.create_reference_from_object(point4)', 'object', 'Part', '2025-10-09 13:07:26'),
    (83, 'create_guide_spline6', 'Create Reference From Object on Part', 2, 'PyCATIA function for create_reference_from_object on Part', 'part', 'create_reference_from_object', 'part.create_reference_from_object(point2)', 'object', 'Part', '2025-10-09 13:07:26'),
    (84, 'create_guide_spline6', 'Create Reference From Object on Part', 3, 'PyCATIA function for create_reference_from_object on Part', 'part', 'create_reference_from_object', 'part.create_reference_from_object(y_axis)', 'object', 'Part', '2025-10-09 13:07:26'),
    (85, 'create_guide_spline6', 'Create Spline', 1, 'PyCATIA function for add_new_spline on HybridShapeFactory', 'hybrid_shape_factory', 'add_new_spline', 'hybrid_shape_factory.add_new_spline()', "<class 'pycatia.hybrid_shape_interfaces.hybrid_shape_spline.HybridShapeSpline'>", 'HybridShapeFactory', '2025-10-09 13:07:26'),
    (86, 'create_guide_spline6', "Add Point With Constraint From Curve on <Class 'Pycatia.Hybrid Shape Interfaces.Hybrid Shape Spline.Hybridshapespline'>", 1, "PyCATIA function for add_point_with_constraint_from_curve on <class 'pycatia.hybrid_shape_interfaces.hybrid_shape_spline.HybridShapeSpline'>", 'spline6', 'add_point_with_constraint_from_curve', 'spline6.add_point_with_constraint_from_curve(ref_point4, ref_y_axis, 1, 1, 1)', 'None', "<class 'pycatia.hybrid_shape_interfaces.hybrid_shape_spline.HybridShapeSpline'>", '2025-10-09 13:07:26'),
    (87, 'create_guide_spline6', "Add Point With Constraint From Curve on <Class 'Pycatia.Hybrid Shape Interfaces.Hybrid Shape Spline.Hybridshapespline'>", 2, "PyCATIA function for add_point_with_constraint_from_curve on <class 'pycatia.hybrid_shape_interfaces.hybrid_shape_spline.HybridShapeSpline'>", 'spline6', 'add_point_with_constraint_from_curve', 'spline6.add_point_with_constraint_from_curve(ref_point2, ref_y_axis, 1, 1, 1)', 'None', "<class 'pycatia.hybrid_shape_interfaces.hybrid_shape_spline.HybridShapeSpline'>", '2025-10-09 13:07:26'),
    (88, 'create_guide_spline6', "Append Hybrid Shape on <Class 'Pycatia.Mec Mod Interfaces.Hybrid Body.Hybridbody'>", 1, "PyCATIA function for append_hybrid_shape on <class 'pycatia.mec_mod_interfaces.hybrid_body.HybridBody'>", 'geom_set', 'append_hybrid_shape', 'geom_set.append_hybrid_shape(spline6)', 'None', "<class 'pycatia.mec_mod_interfaces.hybrid_body.HybridBody'>", '2025-10-09 13:07:26'),
    (89, 'create_guide_spline6', 'Update Part', 1, 'PyCATIA function for update on Part', 'part', 'update', 'part.update()', 'None', 'Part', '2025-10-09 13:07:26'),
    (90, 'create_extrude_surface', 'Create Direction', 3, 'PyCATIA function for add_new_direction on HybridShapeFactory', 'hybrid_shape_factory', 'add_new_direction', 'hybrid_shape_factory.add_new_direction(zx_plane)', "<class 'pycatia.hybrid_shape_interfaces.hybrid_shape_direction.HybridShapeDirection'>", 'HybridShapeFactory', '2025-10-09 13:07:26'),
    (91, 'create_extrude_surface', 'Create Extrude', 3, 'PyCATIA function for add_new_extrude on HybridShapeFactory', 'hybrid_shape_factory', 'add_new_extrude', 'hybrid_shape_factory.add_new_extrude(spline3, -30.0, 0.0, dir_zx_plane)', "<class 'pycatia.hybrid_shape_interfaces.hybrid_shape_extrude.HybridShapeExtrude'>", 'HybridShapeFactory', '2025-10-09 13:07:26'),
    (92, 'create_extrude_surface', "Append Hybrid Shape on <Class 'Pycatia.Mec Mod Interfaces.Hybrid Body.Hybridbody'>", 3, "PyCATIA function for append_hybrid_shape on <class 'pycatia.mec_mod_interfaces.hybrid_body.HybridBody'>", 'geom_set', 'append_hybrid_shape', 'geom_set.append_hybrid_shape(extrude3)', 'None', "<class 'pycatia.mec_mod_interfaces.hybrid_body.HybridBody'>", '2025-10-09 13:07:26'),
    (93, 'create_extrude_surface', 'Update Part', 3, 'PyCATIA function for update on Part', 'part', 'update', 'part.update()', 'None', 'Part', '2025-10-09 13:07:26'),
    (94, 'create_extrude_surface', 'Create Direction', 4, 'PyCATIA function for add_new_direction on HybridShapeFactory', 'hybrid_shape_factory', 'add_new_direction', 'hybrid_shape_factory.add_new_direction(zx_plane)', "<class 'pycatia.hybrid_shape_interfaces.hybrid_shape_direction.HybridShapeDirection'>", 'HybridShapeFactory', '2025-10-09 13:07:26'),
    (95, 'create_extrude_surface', 'Create Extrude', 4, 'PyCATIA function for add_new_extrude on HybridShapeFactory', 'hybrid_shape_factory', 'add_new_extrude', 'hybrid_shape_factory.add_new_extrude(spline4, -30.0, 0.0, dir_zx_plane)', "<class 'pycatia.hybrid_shape_interfaces.hybrid_shape_extrude.HybridShapeExtrude'>", 'HybridShapeFactory', '2025-10-09 13:07:26'),
    (96, 'create_extrude_surface', "Append Hybrid Shape on <Class 'Pycatia.Mec Mod Interfaces.Hybrid Body.Hybridbody'>", 4, "PyCATIA function for append_hybrid_shape on <class 'pycatia.mec_mod_interfaces.hybrid_body.HybridBody'>", 'geom_set', 'append_hybrid_shape', 'geom_set.append_hybrid_shape(extrude4)', 'None', "<class 'pycatia.mec_mod_interfaces.hybrid_body.HybridBody'>", '2025-10-09 13:07:26'),
    (97, 'create_extrude_surface', 'Update Part', 4, 'PyCATIA function for update on Part', 'part', 'update', 'part.update()', 'None', 'Part', '2025-10-09 13:07:26'),
    (98, 'create_upper_loft_surface', 'Create Reference From Object on Part', 1, 'PyCATIA function for create_reference_from_object on Part', 'part', 'create_reference_from_object', 'part.create_reference_from_object(spline2)', 'object', 'Part', '2025-10-09 13:07:26'),
    (99, 'create_upper_loft_surface', 'Create Reference From Object on Part', 2, 'PyCATIA function for create_reference_from_object on Part', 'part', 'create_reference_from_object', 'part.create_reference_from_object(spline4)', 'object', 'Part', '2025-10-09 13:07:26'),
    (100, 'create_upper_loft_surface', 'Create Reference From Object on Part', 3, 'PyCATIA function for create_reference_from_object on Part', 'part', 'create_reference_from_object', 'part.create_reference_from_object(spline5)', 'object', 'Part', '2025-10-09 13:07:26'),
    (101, 'create_upper_loft_surface', 'Create Reference From Object on Part', 4, 'PyCATIA function for create_reference_from_object on Part', 'part', 'create_reference_from_object', 'part.create_reference_from_object(spline6)', 'object', 'Part', '2025-10-09 13:07:26'),
    (102, 'create_upper_loft_surface', 'Create Reference From Object on Part', 5, 'PyCATIA function for create_reference_from_object on Part', 'part', 'create_reference_from_object', 'part.create_reference_from_object(extrude2)', 'object', 'Part', '2025-10-09 13:07:26'),
    (103, 'create_upper_loft_surface', 'Create Reference From Object on Part', 6, 'PyCATIA function for create_reference_from_object on Part', 'part', 'create_reference_from_object', 'part.create_reference_from_object(extrude3)', 'object', 'Part', '2025-10-09 13:07:26'),
    (104, 'create_upper_loft_surface', 'Create Reference From Object on Part', 7, 'PyCATIA function for create_reference_from_object on Part', 'part', 'create_reference_from_object', 'part.create_reference_from_object(point2)', 'object', 'Part', '2025-10-09 13:07:26'),
    (105, 'create_upper_loft_surface', 'Create Reference From Object on Part', 8, 'PyCATIA function for create_reference_from_object on Part', 'part', 'create_reference_from_object', 'part.create_reference_from_object(point4)', 'object', 'Part', '2025-10-09 13:07:26'),
    (106, 'create_upper_loft_surface', 'Create Loft', 1, 'PyCATIA function for add_new_loft on HybridShapeFactory', 'hybrid_shape_factory', 'add_new_loft', 'hybrid_shape_factory.add_new_loft()', "<class 'pycatia.hybrid_shape_interfaces.hybrid_shape_loft.HybridShapeLoft'>", 'HybridShapeFactory', '2025-10-09 13:07:26'),
    (107, 'create_upper_loft_surface', "Add Section To Loft on <Class 'Pycatia.Hybrid Shape Interfaces.Hybrid Shape Loft.Hybridshapeloft'>", 1, "PyCATIA function for add_section_to_loft on <class 'pycatia.hybrid_shape_interfaces.hybrid_shape_loft.HybridShapeLoft'>", 'loft_surface1', 'add_section_to_loft', 'loft_surface1.add_section_to_loft(ref_spline4, 1, ref_closingpoint4)', 'None', "<class 'pycatia.hybrid_shape_interfaces.hybrid_shape_loft.HybridShapeLoft'>", '2025-10-09 13:07:26'),
    (108, 'create_upper_loft_surface', "Set Start Face For Closing on <Class 'Pycatia.Hybrid Shape Interfaces.Hybrid Shape Loft.Hybridshapeloft'>", 1, "PyCATIA function for set_start_face_for_closing on <class 'pycatia.hybrid_shape_interfaces.hybrid_shape_loft.HybridShapeLoft'>", 'loft_surface1', 'set_start_face_for_closing', 'loft_surface1.set_start_face_for_closing(ref_extrude3)', 'None', "<class 'pycatia.hybrid_shape_interfaces.hybrid_shape_loft.HybridShapeLoft'>", '2025-10-09 13:07:26'),
    (109, 'create_upper_loft_surface', "Add Section To Loft on <Class 'Pycatia.Hybrid Shape Interfaces.Hybrid Shape Loft.Hybridshapeloft'>", 2, "PyCATIA function for add_section_to_loft on <class 'pycatia.hybrid_shape_interfaces.hybrid_shape_loft.HybridShapeLoft'>", 'loft_surface1', 'add_section_to_loft', 'loft_surface1.add_section_to_loft(ref_spline2, 1, ref_closingpoint2)', 'None', "<class 'pycatia.hybrid_shape_interfaces.hybrid_shape_loft.HybridShapeLoft'>", '2025-10-09 13:07:26'),
    (110, 'create_upper_loft_surface', "Set End Face For Closing on <Class 'Pycatia.Hybrid Shape Interfaces.Hybrid Shape Loft.Hybridshapeloft'>", 1, "PyCATIA function for set_end_face_for_closing on <class 'pycatia.hybrid_shape_interfaces.hybrid_shape_loft.HybridShapeLoft'>", 'loft_surface1', 'set_end_face_for_closing', 'loft_surface1.set_end_face_for_closing(ref_extrude2)', 'None', "<class 'pycatia.hybrid_shape_interfaces.hybrid_shape_loft.HybridShapeLoft'>", '2025-10-09 13:07:26'),
    (111, 'create_upper_loft_surface', "Remove Section Point on <Class 'Pycatia.Hybrid Shape Interfaces.Hybrid Shape Loft.Hybridshapeloft'>", 1, "PyCATIA function for remove_section_point on <class 'pycatia.hybrid_shape_interfaces.hybrid_shape_loft.HybridShapeLoft'>", 'loft_surface1', 'remove_section_point', 'loft_surface1.remove_section_point(ref_spline4)', 'None', "<class 'pycatia.hybrid_shape_interfaces.hybrid_shape_loft.HybridShapeLoft'>", '2025-10-09 13:07:26'),
    (112, 'create_upper_loft_surface', "Remove Section Point on <Class 'Pycatia.Hybrid Shape Interfaces.Hybrid Shape Loft.Hybridshapeloft'>", 2, "PyCATIA function for remove_section_point on <class 'pycatia.hybrid_shape_interfaces.hybrid_shape_loft.HybridShapeLoft'>", 'loft_surface1', 'remove_section_point', 'loft_surface1.remove_section_point(ref_spline2)', 'None', "<class 'pycatia.hybrid_shape_interfaces.hybrid_shape_loft.HybridShapeLoft'>", '2025-10-09 13:07:26'),
    (113, 'create_upper_loft_surface', "Add Guide on <Class 'Pycatia.Hybrid Shape Interfaces.Hybrid Shape Loft.Hybridshapeloft'>", 1, "PyCATIA function for add_guide on <class 'pycatia.hybrid_shape_interfaces.hybrid_shape_loft.HybridShapeLoft'>", 'loft_surface1', 'add_guide', 'loft_surface1.add_guide(ref_spline5)', 'None', "<class 'pycatia.hybrid_shape_interfaces.hybrid_shape_loft.HybridShapeLoft'>", '2025-10-09 13:07:26'),
    (114, 'create_upper_loft_surface', "Add Guide on <Class 'Pycatia.Hybrid Shape Interfaces.Hybrid Shape Loft.Hybridshapeloft'>", 2, "PyCATIA function for add_guide on <class 'pycatia.hybrid_shape_interfaces.hybrid_shape_loft.HybridShapeLoft'>", 'loft_surface1', 'add_guide', 'loft_surface1.add_guide(ref_spline6)', 'None', "<class 'pycatia.hybrid_shape_interfaces.hybrid_shape_loft.HybridShapeLoft'>", '2025-10-09 13:07:26'),
    (115, 'create_upper_loft_surface', "Append Hybrid Shape on <Class 'Pycatia.Mec Mod Interfaces.Hybrid Body.Hybridbody'>", 1, "PyCATIA function for append_hybrid_shape on <class 'pycatia.mec_mod_interfaces.hybrid_body.HybridBody'>", 'geom_set', 'append_hybrid_shape', 'geom_set.append_hybrid_shape(loft_surface1)', 'None', "<class 'pycatia.mec_mod_interfaces.hybrid_body.HybridBody'>", '2025-10-09 13:07:26'),
    (116, 'create_upper_loft_surface', 'Update Part', 1, 'PyCATIA function for update on Part', 'part', 'update', 'part.update()', 'None', 'Part', '2025-10-09 13:07:26'),
    (117, 'create_lower_loft_surface', 'Create Reference From Object on Part', 1, 'PyCATIA function for create_reference_from_object on Part', 'part', 'create_reference_from_object', 'part.create_reference_from_object(spline1)', 'object', 'Part', '2025-10-09 13:07:26'),
    (118, 'create_lower_loft_surface', 'Create Reference From Object on Part', 2, 'PyCATIA function for create_reference_from_object on Part', 'part', 'create_reference_from_object', 'part.create_reference_from_object(spline3)', 'object', 'Part', '2025-10-09 13:07:26'),
    (119, 'create_lower_loft_surface', 'Create Reference From Object on Part', 3, 'PyCATIA function for create_reference_from_object on Part', 'part', 'create_reference_from_object', 'part.create_reference_from_object(spline5)', 'object', 'Part', '2025-10-09 13:07:26'),
    (120, 'create_lower_loft_surface', 'Create Reference From Object on Part', 4, 'PyCATIA function for create_reference_from_object on Part', 'part', 'create_reference_from_object', 'part.create_reference_from_object(spline6)', 'object', 'Part', '2025-10-09 13:07:26'),
    (121, 'create_lower_loft_surface', 'Create Reference From Object on Part', 5, 'PyCATIA function for create_reference_from_object on Part', 'part', 'create_reference_from_object', 'part.create_reference_from_object(point1)', 'object', 'Part', '2025-10-09 13:07:26'),
    (122, 'create_lower_loft_surface', 'Create Reference From Object on Part', 6, 'PyCATIA function for create_reference_from_object on Part', 'part', 'create_reference_from_object', 'part.create_reference_from_object(point3)', 'object', 'Part', '2025-10-09 13:07:26'),
    (123, 'create_lower_loft_surface', 'Create Reference From Object on Part', 7, 'PyCATIA function for create_reference_from_object on Part', 'part', 'create_reference_from_object', 'part.create_reference_from_object(extrude4)', 'object', 'Part', '2025-10-09 13:07:26'),
    (124, 'create_lower_loft_surface', 'Create Reference From Geometry on Part', 1, 'PyCATIA function for create_reference_from_geometry on Part', 'part', 'create_reference_from_geometry', 'part.create_reference_from_geometry(extrude1)', "<class 'pycatia.in_interfaces.reference.Reference'>", 'Part', '2025-10-09 13:07:26'),
    (125, 'create_lower_loft_surface', 'Create Loft', 1, 'PyCATIA function for add_new_loft on HybridShapeFactory', 'hybrid_shape_factory', 'add_new_loft', 'hybrid_shape_factory.add_new_loft()', "<class 'pycatia.hybrid_shape_interfaces.hybrid_shape_loft.HybridShapeLoft'>", 'HybridShapeFactory', '2025-10-09 13:07:26'),
    (126, 'create_lower_loft_surface', "Add Section To Loft on <Class 'Pycatia.Hybrid Shape Interfaces.Hybrid Shape Loft.Hybridshapeloft'>", 1, "PyCATIA function for add_section_to_loft on <class 'pycatia.hybrid_shape_interfaces.hybrid_shape_loft.HybridShapeLoft'>", 'loft_surface2', 'add_section_to_loft', 'loft_surface2.add_section_to_loft(ref_spline3, 1, ref_closingpoint3)', 'None', "<class 'pycatia.hybrid_shape_interfaces.hybrid_shape_loft.HybridShapeLoft'>", '2025-10-09 13:07:26'),
    (127, 'create_lower_loft_surface', "Set Start Face For Closing on <Class 'Pycatia.Hybrid Shape Interfaces.Hybrid Shape Loft.Hybridshapeloft'>", 1, "PyCATIA function for set_start_face_for_closing on <class 'pycatia.hybrid_shape_interfaces.hybrid_shape_loft.HybridShapeLoft'>", 'loft_surface2', 'set_start_face_for_closing', 'loft_surface2.set_start_face_for_closing(ref_extrude4)', 'None', "<class 'pycatia.hybrid_shape_interfaces.hybrid_shape_loft.HybridShapeLoft'>", '2025-10-09 13:07:26'),
    (128, 'create_lower_loft_surface', "Add Section To Loft on <Class 'Pycatia.Hybrid Shape Interfaces.Hybrid Shape Loft.Hybridshapeloft'>", 2, "PyCATIA function for add_section_to_loft on <class 'pycatia.hybrid_shape_interfaces.hybrid_shape_loft.HybridShapeLoft'>", 'loft_surface2', 'add_section_to_loft', 'loft_surface2.add_section_to_loft(ref_spline1, 1, ref_closingpoint1)', 'None', "<class 'pycatia.hybrid_shape_interfaces.hybrid_shape_loft.HybridShapeLoft'>", '2025-10-09 13:07:26'),
    (129, 'create_lower_loft_surface', "Set End Face For Closing on <Class 'Pycatia.Hybrid Shape Interfaces.Hybrid Shape Loft.Hybridshapeloft'>", 1, "PyCATIA function for set_end_face_for_closing on <class 'pycatia.hybrid_shape_interfaces.hybrid_shape_loft.HybridShapeLoft'>", 'loft_surface2', 'set_end_face_for_closing', 'loft_surface2.set_end_face_for_closing(ref_extrude1)', 'None', "<class 'pycatia.hybrid_shape_interfaces.hybrid_shape_loft.HybridShapeLoft'>", '2025-10-09 13:07:26'),
    (130, 'create_lower_loft_surface', "Remove Section Point on <Class 'Pycatia.Hybrid Shape Interfaces.Hybrid Shape Loft.Hybridshapeloft'>", 1, "PyCATIA function for remove_section_point on <class 'pycatia.hybrid_shape_interfaces.hybrid_shape_loft.HybridShapeLoft'>", 'loft_surface2', 'remove_section_point', 'loft_surface2.remove_section_point(ref_spline3)', 'None', "<class 'pycatia.hybrid_shape_interfaces.hybrid_shape_loft.HybridShapeLoft'>", '2025-10-09 13:07:26'),
    (131, 'create_lower_loft_surface', "Remove Section Point on <Class 'Pycatia.Hybrid Shape Interfaces.Hybrid Shape Loft.Hybridshapeloft'>", 2, "PyCATIA function for remove_section_point on <class 'pycatia.hybrid_shape_interfaces.hybrid_shape_loft.HybridShapeLoft'>", 'loft_surface2', 'remove_section_point', 'loft_surface2.remove_section_point(ref_spline1)', 'None', "<class 'pycatia.hybrid_shape_interfaces.hybrid_shape_loft.HybridShapeLoft'>", '2025-10-09 13:07:26'),
    (132, 'create_lower_loft_surface', "Add Guide on <Class 'Pycatia.Hybrid Shape Interfaces.Hybrid Shape Loft.Hybridshapeloft'>", 1, "PyCATIA function for add_guide on <class 'pycatia.hybrid_shape_interfaces.hybrid_shape_loft.HybridShapeLoft'>", 'loft_surface2', 'add_guide', 'loft_surface2.add_guide(ref_spline5)', 'None', "<class 'pycatia.hybrid_shape_interfaces.hybrid_shape_loft.HybridShapeLoft'>", '2025-10-09 13:07:26'),
    (133, 'create_lower_loft_surface', "Add Guide on <Class 'Pycatia.Hybrid Shape Interfaces.Hybrid Shape Loft.Hybridshapeloft'>", 2, "PyCATIA function for add_guide on <class 'pycatia.hybrid_shape_interfaces.hybrid_shape_loft.HybridShapeLoft'>", 'loft_surface2', 'add_guide', 'loft_surface2.add_guide(ref_spline6)', 'None', "<class 'pycatia.hybrid_shape_interfaces.hybrid_shape_loft.HybridShapeLoft'>", '2025-10-09 13:07:26'),
    (134, 'create_lower_loft_surface', "Append Hybrid Shape on <Class 'Pycatia.Mec Mod Interfaces.Hybrid Body.Hybridbody'>", 1, "PyCATIA function for append_hybrid_shape on <class 'pycatia.mec_mod_interfaces.hybrid_body.HybridBody'>", 'geom_set', 'append_hybrid_shape', 'geom_set.append_hybrid_shape(loft_surface2)', 'None', "<class 'pycatia.mec_mod_interfaces.hybrid_body.HybridBody'>", '2025-10-09 13:07:26'),
    (135, 'create_lower_loft_surface', 'Update Part', 1, 'PyCATIA function for update on Part', 'part', 'update', 'part.update()', 'None', 'Part', '2025-10-09 13:07:26'),
    (136, 'create_join_surface', 'Create Reference From Object on Part', 1, 'PyCATIA function for create_reference_from_object on Part', 'part', 'create_reference_from_object', 'part.create_reference_from_object(extrude1)', 'object', 'Part', '2025-10-09 13:07:26'),
    (137, 'create_join_surface', 'Create Reference From Object on Part', 2, 'PyCATIA function for create_reference_from_object on Part', 'part', 'create_reference_from_object', 'part.create_reference_from_object(extrude2)', 'object', 'Part', '2025-10-09 13:07:26'),
    (138, 'create_join_surface', 'Create Join', 1, 'PyCATIA function for add_new_join on HybridShapeFactory', 'hybrid_shape_factory', 'add_new_join', 'hybrid_shape_factory.add_new_join(ref_extrude1, ref_extrude2)', "<class 'pycatia.hybrid_shape_interfaces.hybrid_shape_assemble.HybridShapeAssemble'>", 'HybridShapeFactory', '2025-10-09 13:07:26'),
    (139, 'create_join_surface', "Append Hybrid Shape on <Class 'Pycatia.Mec Mod Interfaces.Hybrid Body.Hybridbody'>", 1, "PyCATIA function for append_hybrid_shape on <class 'pycatia.mec_mod_interfaces.hybrid_body.HybridBody'>", 'geom_set', 'append_hybrid_shape', 'geom_set.append_hybrid_shape(join_operation1)', 'None', "<class 'pycatia.mec_mod_interfaces.hybrid_body.HybridBody'>", '2025-10-09 13:07:26'),
    (140, 'create_join_surface', 'Update Part', 1, 'PyCATIA function for update on Part', 'part', 'update', 'part.update()', 'None', 'Part', '2025-10-09 13:07:26'),
    (141, 'create_join_surface', 'Create Reference From Object on Part', 3, 'PyCATIA function for create_reference_from_object on Part', 'part', 'create_reference_from_object', 'part.create_reference_from_object(loft_surface1)', 'object', 'Part', '2025-10-09 13:07:26'),
    (142, 'create_join_surface', 'Create Reference From Object on Part', 4, 'PyCATIA function for create_reference_from_object on Part', 'part', 'create_reference_from_object', 'part.create_reference_from_object(loft_surface2)', 'object', 'Part', '2025-10-09 13:07:26'),
    (143, 'create_join_surface', 'Create Join', 2, 'PyCATIA function for add_new_join on HybridShapeFactory', 'hybrid_shape_factory', 'add_new_join', 'hybrid_shape_factory.add_new_join(ref_loft1, ref_loft2)', "<class 'pycatia.hybrid_shape_interfaces.hybrid_shape_assemble.HybridShapeAssemble'>", 'HybridShapeFactory', '2025-10-09 13:07:26'),
    (144, 'create_join_surface', "Append Hybrid Shape on <Class 'Pycatia.Mec Mod Interfaces.Hybrid Body.Hybridbody'>", 2, "PyCATIA function for append_hybrid_shape on <class 'pycatia.mec_mod_interfaces.hybrid_body.HybridBody'>", 'geom_set', 'append_hybrid_shape', 'geom_set.append_hybrid_shape(join_operation2)', 'None', "<class 'pycatia.mec_mod_interfaces.hybrid_body.HybridBody'>", '2025-10-09 13:07:26'),
    (145, 'create_join_surface', 'Update Part', 2, 'PyCATIA function for update on Part', 'part', 'update', 'part.update()', 'None', 'Part', '2025-10-09 13:07:26'),
    (146, 'create_join_surface', 'Create Reference From Object on Part', 5, 'PyCATIA function for create_reference_from_object on Part', 'part', 'create_reference_from_object', 'part.create_reference_from_object(join_operation1)', 'object', 'Part', '2025-10-09 13:07:26'),
    (147, 'create_join_surface', 'Create Reference From Object on Part', 6, 'PyCATIA function for create_reference_from_object on Part', 'part', 'create_reference_from_object', 'part.create_reference_from_object(join_operation2)', 'object', 'Part', '2025-10-09 13:07:26'),
    (148, 'create_join_surface', 'Create Join', 3, 'PyCATIA function for add_new_join on HybridShapeFactory', 'hybrid_shape_factory', 'add_new_join', 'hybrid_shape_factory.add_new_join(ref_join1, ref_join2)', "<class 'pycatia.hybrid_shape_interfaces.hybrid_shape_assemble.HybridShapeAssemble'>", 'HybridShapeFactory', '2025-10-09 13:07:26'),
    (149, 'create_join_surface', "Append Hybrid Shape on <Class 'Pycatia.Mec Mod Interfaces.Hybrid Body.Hybridbody'>", 3, "PyCATIA function for append_hybrid_shape on <class 'pycatia.mec_mod_interfaces.hybrid_body.HybridBody'>", 'geom_set', 'append_hybrid_shape', 'geom_set.append_hybrid_shape(final_join)', 'None', "<class 'pycatia.mec_mod_interfaces.hybrid_body.HybridBody'>", '2025-10-09 13:07:26'),
    (150, 'create_join_surface', 'Update Part', 3, 'PyCATIA function for update on Part', 'part', 'update', 'part.update()', 'None', 'Part', '2025-10-09 13:07:26'),
    (151, 'add_thickness', 'Create Reference From Object on Part', 1, 'PyCATIA function for create_reference_from_object on Part', 'part', 'create_reference_from_object', 'part.create_reference_from_object(final_join)', 'object', 'Part', '2025-10-09 13:07:26'),
    (152, 'add_thickness', 'Create Volume Thick Surface', 1, 'PyCATIA function for add_new_volume_thick_surface on ShapeFactory', 'shape_factory', 'add_new_volume_thick_surface', 'shape_factory.add_new_volume_thick_surface(ref_final_join, 0, 10.0, 0.0)', "<class 'pycatia.part_interfaces.thick_surface.ThickSurface'>", 'ShapeFactory', '2025-10-09 13:07:26'),
    (153, 'add_thickness', 'Update Part', 1, 'PyCATIA function for update on Part', 'part', 'update', 'part.update()', 'None', 'Part', '2025-10-09 13:07:26'),
    (154, 'mirror_wing', 'Create Reference From Object on Part', 1, 'PyCATIA function for create_reference_from_object on Part', 'part', 'create_reference_from_object', 'part.create_reference_from_object(zx_plane)', 'object', 'Part', '2025-10-09 13:07:26'),
    (155, 'mirror_wing', 'Create Symmetry', 1, 'PyCATIA function for add_new_symmetry on HybridShapeFactory', 'hybrid_shape_factory', 'add_new_symmetry', 'hybrid_shape_factory.add_new_symmetry(thick_surface1, ref_zx_plane)', "<class 'pycatia.hybrid_shape_interfaces.hybrid_shape_symmetry.HybridShapeSymmetry'>", 'HybridShapeFactory', '2025-10-09 13:07:26'),
    (156, 'mirror_wing', "Append Hybrid Shape on <Class 'Pycatia.Mec Mod Interfaces.Hybrid Body.Hybridbody'>", 1, "PyCATIA function for append_hybrid_shape on <class 'pycatia.mec_mod_interfaces.hybrid_body.HybridBody'>", 'geom_set', 'append_hybrid_shape', 'geom_set.append_hybrid_shape(symmetry1)', 'None', "<class 'pycatia.mec_mod_interfaces.hybrid_body.HybridBody'>", '2025-10-09 13:07:26'),
    (157, 'mirror_wing', 'Update Part', 1, 'PyCATIA function for update on Part', 'part', 'update', 'part.update()', 'None', 'Part', '2025-10-09 13:07:26'),
    (158, 'control_element_visibility', 'Item on Hybridshapes', 1, 'PyCATIA function for item on HybridShapes', 'hybrid_shapes', 'item', 'hybrid_shapes.item(element_name)', "<class 'pycatia.mec_mod_interfaces.hybrid_shape.HybridShape'>", 'HybridShapes', '2025-10-09 13:07:26'),
    (159, 'control_element_visibility', 'Create Selection', 1, 'PyCATIA function for add on Selection', 'selection', 'add', 'selection.add(hybrid_shape)', 'None', 'Selection', '2025-10-09 13:07:26'),
    (160, 'control_element_visibility', 'Set Show on Vispropertyset', 1, 'PyCATIA function for set_show on VisPropertySet', 'vis_properties', 'set_show', 'vis_properties.set_show(1)', 'None', 'VisPropertySet', '2025-10-09 13:07:26'),
    (161, 'control_element_visibility', 'Clear on Selection', 1, 'PyCATIA function for clear on Selection', 'selection', 'clear', 'selection.clear()', 'None', 'Selection', '2025-10-09 13:07:26'),
    (162, 'control_element_visibility', 'Clear on Selection', 2, 'PyCATIA function for clear on Selection', 'selection', 'clear', 'selection.clear()', 'None', 'Selection', '2025-10-09 13:07:26'),
    (163, 'initialize_catia_app', 'Catia on Function', 1, 'PyCATIA function for catia on function', '', 'catia', 'catia()', "<class 'pycatia.in_interfaces.application.Application'>", 'function', '2025-10-09 13:21:05'),
    (164, 'initialize_catia_app', 'Start Workbench on Application', 1, 'PyCATIA function for start_workbench on Application', 'caa', 'start_workbench', "caa.start_workbench('GenerativeShapeDesignWorkbench')", 'None', 'Application', '2025-10-09 13:21:05'),
    (165, 'create_point_geometry', 'Create Point Coord', 1, 'PyCATIA function for add_new_point_coord on HybridShapeFactory', 'hybrid_shape_factory', 'add_new_point_coord', 'hybrid_shape_factory.add_new_point_coord(-300, 0.0, 0.0)', "<class 'pycatia.hybrid_shape_interfaces.hybrid_shape_point_coord.HybridShapePointCoord'>", 'HybridShapeFactory', '2025-10-09 13:21:05'),
    (166, 'create_point_geometry', 'Create Point Coord', 2, 'PyCATIA function for add_new_point_coord on HybridShapeFactory', 'hybrid_shape_factory', 'add_new_point_coord', 'hybrid_shape_factory.add_new_point_coord(1000, 0.0, 0.0)', "<class 'pycatia.hybrid_shape_interfaces.hybrid_shape_point_coord.HybridShapePointCoord'>", 'HybridShapeFactory', '2025-10-09 13:21:05'),
    (167, 'create_extrude_surface', 'Create Direction', 1, 'PyCATIA function for add_new_direction on HybridShapeFactory', 'hybrid_shape_factory', 'add_new_direction', 'hybrid_shape_factory.add_new_direction(zx_plane)', "<class 'pycatia.hybrid_shape_interfaces.hybrid_shape_direction.HybridShapeDirection'>", 'HybridShapeFactory', '2025-10-09 13:21:05'),
    (168, 'create_extrude_surface', 'Create Extrude', 1, 'PyCATIA function for add_new_extrude on HybridShapeFactory', 'hybrid_shape_factory', 'add_new_extrude', 'hybrid_shape_factory.add_new_extrude(spline3, -30.0, 0.0, dir_zx_plane)', "<class 'pycatia.hybrid_shape_interfaces.hybrid_shape_extrude.HybridShapeExtrude'>", 'HybridShapeFactory', '2025-10-09 13:21:05'),
    (169, 'create_extrude_surface', 'Create Direction', 2, 'PyCATIA function for add_new_direction on HybridShapeFactory', 'hybrid_shape_factory', 'add_new_direction', 'hybrid_shape_factory.add_new_direction(zx_plane)', "<class 'pycatia.hybrid_shape_interfaces.hybrid_shape_direction.HybridShapeDirection'>", 'HybridShapeFactory', '2025-10-09 13:21:05'),
    (170, 'create_extrude_surface', 'Create Extrude', 2, 'PyCATIA function for add_new_extrude on HybridShapeFactory', 'hybrid_shape_factory', 'add_new_extrude', 'hybrid_shape_factory.add_new_extrude(spline4, -30.0, 0.0, dir_zx_plane)', "<class 'pycatia.hybrid_shape_interfaces.hybrid_shape_extrude.HybridShapeExtrude'>", 'HybridShapeFactory', '2025-10-09 13:21:05'),
]

# Parameter data structure: (id, function_id, parameter_name, parameter_type, parameter_value, 
# is_required, parameter_order, description, example_values, validation_rules)
PARAMETERS_DATA = [
    (1, 2, 'param_1', 'str', 'GenerativeShapeDesignWorkbench', 1, 1, 'Parameter 1 for the function', None, None),
    (2, 3, 'param_1', 'str', 'Part', 1, 1, 'Parameter 1 for the function', None, None),
    (3, 5, 'param_1', 'int', '1', 1, 1, 'Parameter 1 for the function', None, None),
    (4, 5, 'param_2', 'int', '0', 1, 2, 'Parameter 2 for the function', None, None),
    (5, 5, 'param_3', 'int', '0', 1, 3, 'Parameter 3 for the function', None, None),
    (6, 6, 'param_1', 'int', '0', 1, 1, 'Parameter 1 for the function', None, None),
    (7, 6, 'param_2', 'int', '1', 1, 2, 'Parameter 2 for the function', None, None),
    (8, 6, 'param_3', 'int', '0', 1, 3, 'Parameter 3 for the function', None, None),
    (9, 7, 'param_1', 'int', '0', 1, 1, 'Parameter 1 for the function', None, None),
    (10, 7, 'param_2', 'int', '0', 1, 2, 'Parameter 2 for the function', None, None),
    (11, 7, 'param_3', 'int', '1', 1, 3, 'Parameter 3 for the function', None, None),
    (12, 8, 'param_1', 'str', 'x_axis', 1, 1, 'Parameter 1 for the function', None, None),
    (13, 9, 'param_1', 'str', 'y_axis', 1, 1, 'Parameter 1 for the function', None, None),
    (14, 10, 'param_1', 'str', 'z_axis', 1, 1, 'Parameter 1 for the function', None, None),
    (15, 12, 'param_1', 'str', 'zx_plane', 1, 1, 'Parameter 1 for the function', None, None),
    (16, 12, 'param_2', 'float', '500.0', 1, 2, 'Parameter 2 for the function', None, None),
    (17, 12, 'param_3', 'bool', 'False', 1, 3, 'Parameter 3 for the function', None, None),
    (18, 13, 'param_1', 'str', 'plane1', 1, 1, 'Parameter 1 for the function', None, None),
    (19, 15, 'param_1', 'str', 'plane1', 1, 1, 'Parameter 1 for the function', None, None),
    (20, 15, 'param_2', 'str', '-250.0', 1, 2, 'Parameter 2 for the function', None, None),
    (21, 15, 'param_3', 'float', '0.0', 1, 3, 'Parameter 3 for the function', None, None),
    (22, 16, 'param_1', 'str', 'point1', 1, 1, 'Parameter 1 for the function', None, None),
    (23, 18, 'param_1', 'str', 'yz_plane', 1, 1, 'Parameter 1 for the function', None, None),
    (24, 19, 'param_1', 'str', 'plane1', 1, 1, 'Parameter 1 for the function', None, None),
    (25, 19, 'param_2', 'str', 'point1', 1, 2, 'Parameter 2 for the function', None, None),
    (26, 19, 'param_3', 'str', 'yz_direction', 1, 3, 'Parameter 3 for the function', None, None),
    (27, 19, 'param_4', 'float', '300.0', 1, 4, 'Parameter 4 for the function', None, None),
    (28, 20, 'param_1', 'str', 'point2', 1, 1, 'Parameter 1 for the function', None, None),
    (29, 22, 'param_1', 'str', 'point1', 1, 1, 'Parameter 1 for the function', None, None),
    (30, 23, 'param_1', 'str', 'z_axis', 1, 1, 'Parameter 1 for the function', None, None),
    (31, 25, 'param_1', 'str', 'ref_point1', 1, 1, 'Parameter 1 for the function', None, None),
    (32, 25, 'param_2', 'str', 'ref_z_axis', 1, 2, 'Parameter 2 for the function', None, None),
    (33, 25, 'param_3', 'float', '0.5', 1, 3, 'Parameter 3 for the function', None, None),
    (34, 25, 'param_4', 'int', '1', 1, 4, 'Parameter 4 for the function', None, None),
    (35, 25, 'param_5', 'int', '1', 1, 5, 'Parameter 5 for the function', None, None),
    (36, 26, 'param_1', 'str', 'point2', 1, 1, 'Parameter 1 for the function', None, None),
    (37, 27, 'param_1', 'str', 'spline1', 1, 1, 'Parameter 1 for the function', None, None),
    (38, 29, 'param_1', 'str', 'point1', 1, 1, 'Parameter 1 for the function', None, None),
    (39, 30, 'param_1', 'str', 'point2', 1, 1, 'Parameter 1 for the function', None, None),
    (40, 31, 'param_1', 'str', 'z_axis', 1, 1, 'Parameter 1 for the function', None, None),
    (41, 33, 'param_1', 'str', 'ref_point2', 1, 1, 'Parameter 1 for the function', None, None),
    (42, 34, 'param_1', 'str', 'ref_point1', 1, 1, 'Parameter 1 for the function', None, None),
    (43, 34, 'param_2', 'str', 'ref_z_axis', 1, 2, 'Parameter 2 for the function', None, None),
    (44, 34, 'param_3', 'float', '0.3', 1, 3, 'Parameter 3 for the function', None, None),
    (45, 34, 'param_4', 'int', '0', 1, 4, 'Parameter 4 for the function', None, None),
    (46, 34, 'param_5', 'int', '1', 1, 5, 'Parameter 5 for the function', None, None),
    (47, 35, 'param_1', 'str', 'spline2', 1, 1, 'Parameter 1 for the function', None, None),
    (48, 37, 'param_1', 'str', 'plane1', 1, 1, 'Parameter 1 for the function', None, None),
    (49, 38, 'param_1', 'str', 'point1', 1, 1, 'Parameter 1 for the function', None, None),
    (50, 38, 'param_2', 'str', 'dir_plane1', 1, 2, 'Parameter 2 for the function', None, None),
    (51, 38, 'param_3', 'float', '0.0', 1, 3, 'Parameter 3 for the function', None, None),
    (52, 38, 'param_4', 'float', '20.0', 1, 4, 'Parameter 4 for the function', None, None),
    (53, 38, 'param_5', 'bool', 'False', 1, 5, 'Parameter 5 for the function', None, None),
    (54, 39, 'param_1', 'str', 'line1', 1, 1, 'Parameter 1 for the function', None, None),
    (55, 41, 'param_1', 'str', 'xy_plane', 1, 1, 'Parameter 1 for the function', None, None),
    (56, 42, 'param_1', 'str', 'line1', 1, 1, 'Parameter 1 for the function', None, None),
    (57, 43, 'param_1', 'str', 'ref_line1', 1, 1, 'Parameter 1 for the function', None, None),
    (58, 43, 'param_2', 'str', 'ref_xy_plane', 1, 2, 'Parameter 2 for the function', None, None),
    (59, 43, 'param_3', 'str', 'point1', 1, 3, 'Parameter 3 for the function', None, None),
    (60, 43, 'param_4', 'bool', 'False', 1, 4, 'Parameter 4 for the function', None, None),
    (61, 43, 'param_5', 'float', '0.0', 1, 5, 'Parameter 5 for the function', None, None),
    (62, 43, 'param_6', 'float', '20.0', 1, 6, 'Parameter 6 for the function', None, None),
    (63, 43, 'param_7', 'str', '-30.0', 1, 7, 'Parameter 7 for the function', None, None),
    (64, 43, 'param_8', 'bool', 'False', 1, 8, 'Parameter 8 for the function', None, None),
    (65, 44, 'param_1', 'str', 'line2', 1, 1, 'Parameter 1 for the function', None, None),
    (66, 46, 'param_1', 'str', 'line2', 1, 1, 'Parameter 1 for the function', None, None),
    (67, 47, 'param_1', 'str', 'spline1', 1, 1, 'Parameter 1 for the function', None, None),
    (68, 47, 'param_2', 'float', '500.0', 1, 2, 'Parameter 2 for the function', None, None),
    (69, 47, 'param_3', 'float', '0.0', 1, 3, 'Parameter 3 for the function', None, None),
    (70, 47, 'param_4', 'str', 'dir_line2', 1, 4, 'Parameter 4 for the function', None, None),
    (71, 48, 'param_1', 'str', 'extrude1', 1, 1, 'Parameter 1 for the function', None, None),
    (72, 50, 'param_1', 'str', 'line2', 1, 1, 'Parameter 1 for the function', None, None),
    (73, 51, 'param_1', 'str', 'spline2', 1, 1, 'Parameter 1 for the function', None, None),
    (74, 51, 'param_2', 'float', '500.0', 1, 2, 'Parameter 2 for the function', None, None),
    (75, 51, 'param_3', 'float', '0.0', 1, 3, 'Parameter 3 for the function', None, None),
    (76, 51, 'param_4', 'str', 'dir_line2', 1, 4, 'Parameter 4 for the function', None, None),
    (77, 52, 'param_1', 'str', 'extrude2', 1, 1, 'Parameter 1 for the function', None, None),
    (78, 54, 'param_1', 'str', '-300', 1, 1, 'Parameter 1 for the function', None, None),
    (79, 54, 'param_2', 'float', '0.0', 1, 2, 'Parameter 2 for the function', None, None),
    (80, 54, 'param_3', 'float', '0.0', 1, 3, 'Parameter 3 for the function', None, None),
    (81, 55, 'param_1', 'str', 'point3', 1, 1, 'Parameter 1 for the function', None, None),
    (82, 57, 'param_1', 'int', '1000', 1, 1, 'Parameter 1 for the function', None, None),
    (83, 57, 'param_2', 'float', '0.0', 1, 2, 'Parameter 2 for the function', None, None),
    (84, 57, 'param_3', 'float', '0.0', 1, 3, 'Parameter 3 for the function', None, None),
    (85, 58, 'param_1', 'str', 'point4', 1, 1, 'Parameter 1 for the function', None, None),
    (86, 60, 'param_1', 'str', 'point3', 1, 1, 'Parameter 1 for the function', None, None),
    (87, 61, 'param_1', 'str', 'z_axis', 1, 1, 'Parameter 1 for the function', None, None),
    (88, 63, 'param_1', 'str', 'ref_point3', 1, 1, 'Parameter 1 for the function', None, None),
    (89, 63, 'param_2', 'str', 'ref_z_axis', 1, 2, 'Parameter 2 for the function', None, None),
    (90, 63, 'param_3', 'float', '0.5', 1, 3, 'Parameter 3 for the function', None, None),
    (91, 63, 'param_4', 'int', '0', 1, 4, 'Parameter 4 for the function', None, None),
    (92, 63, 'param_5', 'int', '1', 1, 5, 'Parameter 5 for the function', None, None),
    (93, 64, 'param_1', 'str', 'point4', 1, 1, 'Parameter 1 for the function', None, None),
    (94, 65, 'param_1', 'str', 'spline3', 1, 1, 'Parameter 1 for the function', None, None),
    (95, 67, 'param_1', 'str', 'point3', 1, 1, 'Parameter 1 for the function', None, None),
    (96, 68, 'param_1', 'str', 'point4', 1, 1, 'Parameter 1 for the function', None, None),
    (97, 69, 'param_1', 'str', 'z_axis', 1, 1, 'Parameter 1 for the function', None, None),
    (98, 71, 'param_1', 'str', 'ref_point4', 1, 1, 'Parameter 1 for the function', None, None),
    (99, 72, 'param_1', 'str', 'ref_point3', 1, 1, 'Parameter 1 for the function', None, None),
    (100, 72, 'param_2', 'str', 'ref_z_axis', 1, 2, 'Parameter 2 for the function', None, None),
    (101, 72, 'param_3', 'float', '0.3', 1, 3, 'Parameter 3 for the function', None, None),
    (102, 72, 'param_4', 'int', '0', 1, 4, 'Parameter 4 for the function', None, None),
    (103, 72, 'param_5', 'int', '1', 1, 5, 'Parameter 5 for the function', None, None),
    (104, 73, 'param_1', 'str', 'spline4', 1, 1, 'Parameter 1 for the function', None, None),
    (105, 75, 'param_1', 'str', 'point3', 1, 1, 'Parameter 1 for the function', None, None),
    (106, 76, 'param_1', 'str', 'y_axis', 1, 1, 'Parameter 1 for the function', None, None),
    (107, 78, 'param_1', 'str', 'ref_point3', 1, 1, 'Parameter 1 for the function', None, None),
    (108, 78, 'param_2', 'str', 'ref_y_axis', 1, 2, 'Parameter 2 for the function', None, None),
    (109, 78, 'param_3', 'int', '1', 1, 3, 'Parameter 3 for the function', None, None),
    (110, 78, 'param_4', 'int', '0', 1, 4, 'Parameter 4 for the function', None, None),
    (111, 78, 'param_5', 'int', '1', 1, 5, 'Parameter 5 for the function', None, None),
    (112, 79, 'param_1', 'str', 'point1', 1, 1, 'Parameter 1 for the function', None, None),
    (113, 79, 'param_2', 'str', 'line2', 1, 2, 'Parameter 2 for the function', None, None),
    (114, 79, 'param_3', 'int', '1', 1, 3, 'Parameter 3 for the function', None, None),
    (115, 79, 'param_4', 'int', '0', 1, 4, 'Parameter 4 for the function', None, None),
    (116, 79, 'param_5', 'int', '1', 1, 5, 'Parameter 5 for the function', None, None),
    (117, 80, 'param_1', 'str', 'spline5', 1, 1, 'Parameter 1 for the function', None, None),
    (118, 82, 'param_1', 'str', 'point4', 1, 1, 'Parameter 1 for the function', None, None),
    (119, 83, 'param_1', 'str', 'point2', 1, 1, 'Parameter 1 for the function', None, None),
    (120, 84, 'param_1', 'str', 'y_axis', 1, 1, 'Parameter 1 for the function', None, None),
    (121, 86, 'param_1', 'str', 'ref_point4', 1, 1, 'Parameter 1 for the function', None, None),
    (122, 86, 'param_2', 'str', 'ref_y_axis', 1, 2, 'Parameter 2 for the function', None, None),
    (123, 86, 'param_3', 'int', '1', 1, 3, 'Parameter 3 for the function', None, None),
    (124, 86, 'param_4', 'int', '1', 1, 4, 'Parameter 4 for the function', None, None),
    (125, 86, 'param_5', 'int', '1', 1, 5, 'Parameter 5 for the function', None, None),
    (126, 87, 'param_1', 'str', 'ref_point2', 1, 1, 'Parameter 1 for the function', None, None),
    (127, 87, 'param_2', 'str', 'ref_y_axis', 1, 2, 'Parameter 2 for the function', None, None),
    (128, 87, 'param_3', 'int', '1', 1, 3, 'Parameter 3 for the function', None, None),
    (129, 87, 'param_4', 'int', '1', 1, 4, 'Parameter 4 for the function', None, None),
    (130, 87, 'param_5', 'int', '1', 1, 5, 'Parameter 5 for the function', None, None),
    (131, 88, 'param_1', 'str', 'spline6', 1, 1, 'Parameter 1 for the function', None, None),
    (132, 90, 'param_1', 'str', 'zx_plane', 1, 1, 'Parameter 1 for the function', None, None),
    (133, 91, 'param_1', 'str', 'spline3', 1, 1, 'Parameter 1 for the function', None, None),
    (134, 91, 'param_2', 'str', '-30.0', 1, 2, 'Parameter 2 for the function', None, None),
    (135, 91, 'param_3', 'float', '0.0', 1, 3, 'Parameter 3 for the function', None, None),
    (136, 91, 'param_4', 'str', 'dir_zx_plane', 1, 4, 'Parameter 4 for the function', None, None),
    (137, 92, 'param_1', 'str', 'extrude3', 1, 1, 'Parameter 1 for the function', None, None),
    (138, 94, 'param_1', 'str', 'zx_plane', 1, 1, 'Parameter 1 for the function', None, None),
    (139, 95, 'param_1', 'str', 'spline4', 1, 1, 'Parameter 1 for the function', None, None),
    (140, 95, 'param_2', 'str', '-30.0', 1, 2, 'Parameter 2 for the function', None, None),
    (141, 95, 'param_3', 'float', '0.0', 1, 3, 'Parameter 3 for the function', None, None),
    (142, 95, 'param_4', 'str', 'dir_zx_plane', 1, 4, 'Parameter 4 for the function', None, None),
    (143, 96, 'param_1', 'str', 'extrude4', 1, 1, 'Parameter 1 for the function', None, None),
    (144, 98, 'param_1', 'str', 'spline2', 1, 1, 'Parameter 1 for the function', None, None),
    (145, 99, 'param_1', 'str', 'spline4', 1, 1, 'Parameter 1 for the function', None, None),
    (146, 100, 'param_1', 'str', 'spline5', 1, 1, 'Parameter 1 for the function', None, None),
    (147, 101, 'param_1', 'str', 'spline6', 1, 1, 'Parameter 1 for the function', None, None),
    (148, 102, 'param_1', 'str', 'extrude2', 1, 1, 'Parameter 1 for the function', None, None),
    (149, 103, 'param_1', 'str', 'extrude3', 1, 1, 'Parameter 1 for the function', None, None),
    (150, 104, 'param_1', 'str', 'point2', 1, 1, 'Parameter 1 for the function', None, None),
    (151, 105, 'param_1', 'str', 'point4', 1, 1, 'Parameter 1 for the function', None, None),
    (152, 107, 'param_1', 'str', 'ref_spline4', 1, 1, 'Parameter 1 for the function', None, None),
    (153, 107, 'param_2', 'int', '1', 1, 2, 'Parameter 2 for the function', None, None),
    (154, 107, 'param_3', 'str', 'ref_closingpoint4', 1, 3, 'Parameter 3 for the function', None, None),
    (155, 108, 'param_1', 'str', 'ref_extrude3', 1, 1, 'Parameter 1 for the function', None, None),
    (156, 109, 'param_1', 'str', 'ref_spline2', 1, 1, 'Parameter 1 for the function', None, None),
    (157, 109, 'param_2', 'int', '1', 1, 2, 'Parameter 2 for the function', None, None),
    (158, 109, 'param_3', 'str', 'ref_closingpoint2', 1, 3, 'Parameter 3 for the function', None, None),
    (159, 110, 'param_1', 'str', 'ref_extrude2', 1, 1, 'Parameter 1 for the function', None, None),
    (160, 111, 'param_1', 'str', 'ref_spline4', 1, 1, 'Parameter 1 for the function', None, None),
    (161, 112, 'param_1', 'str', 'ref_spline2', 1, 1, 'Parameter 1 for the function', None, None),
    (162, 113, 'param_1', 'str', 'ref_spline5', 1, 1, 'Parameter 1 for the function', None, None),
    (163, 114, 'param_1', 'str', 'ref_spline6', 1, 1, 'Parameter 1 for the function', None, None),
    (164, 115, 'param_1', 'str', 'loft_surface1', 1, 1, 'Parameter 1 for the function', None, None),
    (165, 117, 'param_1', 'str', 'spline1', 1, 1, 'Parameter 1 for the function', None, None),
    (166, 118, 'param_1', 'str', 'spline3', 1, 1, 'Parameter 1 for the function', None, None),
    (167, 119, 'param_1', 'str', 'spline5', 1, 1, 'Parameter 1 for the function', None, None),
    (168, 120, 'param_1', 'str', 'spline6', 1, 1, 'Parameter 1 for the function', None, None),
    (169, 121, 'param_1', 'str', 'point1', 1, 1, 'Parameter 1 for the function', None, None),
    (170, 122, 'param_1', 'str', 'point3', 1, 1, 'Parameter 1 for the function', None, None),
    (171, 123, 'param_1', 'str', 'extrude4', 1, 1, 'Parameter 1 for the function', None, None),
    (172, 124, 'param_1', 'str', 'extrude1', 1, 1, 'Parameter 1 for the function', None, None),
    (173, 126, 'param_1', 'str', 'ref_spline3', 1, 1, 'Parameter 1 for the function', None, None),
    (174, 126, 'param_2', 'int', '1', 1, 2, 'Parameter 2 for the function', None, None),
    (175, 126, 'param_3', 'str', 'ref_closingpoint3', 1, 3, 'Parameter 3 for the function', None, None),
    (176, 127, 'param_1', 'str', 'ref_extrude4', 1, 1, 'Parameter 1 for the function', None, None),
    (177, 128, 'param_1', 'str', 'ref_spline1', 1, 1, 'Parameter 1 for the function', None, None),
    (178, 128, 'param_2', 'int', '1', 1, 2, 'Parameter 2 for the function', None, None),
    (179, 128, 'param_3', 'str', 'ref_closingpoint1', 1, 3, 'Parameter 3 for the function', None, None),
    (180, 129, 'param_1', 'str', 'ref_extrude1', 1, 1, 'Parameter 1 for the function', None, None),
    (181, 130, 'param_1', 'str', 'ref_spline3', 1, 1, 'Parameter 1 for the function', None, None),
    (182, 131, 'param_1', 'str', 'ref_spline1', 1, 1, 'Parameter 1 for the function', None, None),
    (183, 132, 'param_1', 'str', 'ref_spline5', 1, 1, 'Parameter 1 for the function', None, None),
    (184, 133, 'param_1', 'str', 'ref_spline6', 1, 1, 'Parameter 1 for the function', None, None),
    (185, 134, 'param_1', 'str', 'loft_surface2', 1, 1, 'Parameter 1 for the function', None, None),
    (186, 136, 'param_1', 'str', 'extrude1', 1, 1, 'Parameter 1 for the function', None, None),
    (187, 137, 'param_1', 'str', 'extrude2', 1, 1, 'Parameter 1 for the function', None, None),
    (188, 138, 'param_1', 'str', 'ref_extrude1', 1, 1, 'Parameter 1 for the function', None, None),
    (189, 138, 'param_2', 'str', 'ref_extrude2', 1, 2, 'Parameter 2 for the function', None, None),
    (190, 139, 'param_1', 'str', 'join_operation1', 1, 1, 'Parameter 1 for the function', None, None),
    (191, 141, 'param_1', 'str', 'loft_surface1', 1, 1, 'Parameter 1 for the function', None, None),
    (192, 142, 'param_1', 'str', 'loft_surface2', 1, 1, 'Parameter 1 for the function', None, None),
    (193, 143, 'param_1', 'str', 'ref_loft1', 1, 1, 'Parameter 1 for the function', None, None),
    (194, 143, 'param_2', 'str', 'ref_loft2', 1, 2, 'Parameter 2 for the function', None, None),
    (195, 144, 'param_1', 'str', 'join_operation2', 1, 1, 'Parameter 1 for the function', None, None),
    (196, 146, 'param_1', 'str', 'join_operation1', 1, 1, 'Parameter 1 for the function', None, None),
    (197, 147, 'param_1', 'str', 'join_operation2', 1, 1, 'Parameter 1 for the function', None, None),
    (198, 148, 'param_1', 'str', 'ref_join1', 1, 1, 'Parameter 1 for the function', None, None),
    (199, 148, 'param_2', 'str', 'ref_join2', 1, 2, 'Parameter 2 for the function', None, None),
    (200, 149, 'param_1', 'str', 'final_join', 1, 1, 'Parameter 1 for the function', None, None),
    (201, 151, 'param_1', 'str', 'final_join', 1, 1, 'Parameter 1 for the function', None, None),
    (202, 152, 'param_1', 'str', 'ref_final_join', 1, 1, 'Parameter 1 for the function', None, None),
    (203, 152, 'param_2', 'int', '0', 1, 2, 'Parameter 2 for the function', None, None),
    (204, 152, 'param_3', 'float', '10.0', 1, 3, 'Parameter 3 for the function', None, None),
    (205, 152, 'param_4', 'float', '0.0', 1, 4, 'Parameter 4 for the function', None, None),
    (206, 154, 'param_1', 'str', 'zx_plane', 1, 1, 'Parameter 1 for the function', None, None),
    (207, 155, 'param_1', 'str', 'thick_surface1', 1, 1, 'Parameter 1 for the function', None, None),
    (208, 155, 'param_2', 'str', 'ref_zx_plane', 1, 2, 'Parameter 2 for the function', None, None),
    (209, 156, 'param_1', 'str', 'symmetry1', 1, 1, 'Parameter 1 for the function', None, None),
    (210, 158, 'param_1', 'str', 'element_name', 1, 1, 'Parameter 1 for the function', None, None),
    (211, 159, 'param_1', 'str', 'hybrid_shape', 1, 1, 'Parameter 1 for the function', None, None),
    (212, 160, 'param_1', 'int', '1', 1, 1, 'Parameter 1 for the function', None, None),
    (213, 164, 'param_1', 'str', 'GenerativeShapeDesignWorkbench', 1, 1, 'Parameter 1 for the function', None, None),
    (214, 165, 'param_1', 'str', '-300', 1, 1, 'Parameter 1 for the function', None, None),
    (215, 165, 'param_2', 'float', '0.0', 1, 2, 'Parameter 2 for the function', None, None),
    (216, 165, 'param_3', 'float', '0.0', 1, 3, 'Parameter 3 for the function', None, None),
    (217, 166, 'param_1', 'int', '1000', 1, 1, 'Parameter 1 for the function', None, None),
    (218, 166, 'param_2', 'float', '0.0', 1, 2, 'Parameter 2 for the function', None, None),
    (219, 166, 'param_3', 'float', '0.0', 1, 3, 'Parameter 3 for the function', None, None),
    (220, 167, 'param_1', 'str', 'zx_plane', 1, 1, 'Parameter 1 for the function', None, None),
    (221, 168, 'param_1', 'str', 'spline3', 1, 1, 'Parameter 1 for the function', None, None),
    (222, 168, 'param_2', 'str', '-30.0', 1, 2, 'Parameter 2 for the function', None, None),
    (223, 168, 'param_3', 'float', '0.0', 1, 3, 'Parameter 3 for the function', None, None),
    (224, 168, 'param_4', 'str', 'dir_zx_plane', 1, 4, 'Parameter 4 for the function', None, None),
    (225, 169, 'param_1', 'str', 'zx_plane', 1, 1, 'Parameter 1 for the function', None, None),
    (226, 170, 'param_1', 'str', 'spline4', 1, 1, 'Parameter 1 for the function', None, None),
    (227, 170, 'param_2', 'str', '-30.0', 1, 2, 'Parameter 2 for the function', None, None),
    (228, 170, 'param_3', 'float', '0.0', 1, 3, 'Parameter 3 for the function', None, None),
    (229, 170, 'param_4', 'str', 'dir_zx_plane', 1, 4, 'Parameter 4 for the function', None, None),
]

# Examples data (currently empty in source database)
EXAMPLES_DATA = []

# Dependencies data (currently empty in source database) 
DEPENDENCIES_DATA = []

# Helper functions for data processing
def get_functions_by_id(function_id: str) -> List[Tuple]:
    """Get all function records with a specific function_id"""
    return [func for func in FUNCTIONS_DATA if func[1] == function_id]

def get_parameters_for_function(function_pk_id: int) -> List[Tuple]:
    """Get all parameters for a specific function (by primary key id)"""
    return [param for param in PARAMETERS_DATA if param[1] == function_pk_id]

def get_unique_function_ids() -> List[str]:
    """Get list of unique function_id values"""
    return list(set([func[1] for func in FUNCTIONS_DATA]))

def get_function_by_name(function_name: str) -> List[Tuple]:
    """Get function records by function name"""
    return [func for func in FUNCTIONS_DATA if func[2] == function_name]

def get_functions_by_object_type(object_type: str) -> List[Tuple]:
    """Get functions by object type (e.g., 'HybridShapeFactory', 'Part', etc.)"""
    return [func for func in FUNCTIONS_DATA if func[9] == object_type]

def validate_function_data(func_data: Tuple) -> bool:
    """Validate function data structure"""
    if len(func_data) != 11:
        return False
    # Check that required fields are not None
    required_fields = [1, 2, 6]  # function_id, function_name, method_name
    return all(func_data[i] is not None for i in required_fields)

def validate_parameter_data(param_data: Tuple) -> bool:
    """Validate parameter data structure"""
    if len(param_data) != 10:
        return False
    # Check that required fields are not None  
    required_fields = [1, 2]  # function_id, parameter_name
    return all(param_data[i] is not None for i in required_fields)

# Data summary information
TOTAL_FUNCTIONS = len(FUNCTIONS_DATA)
TOTAL_PARAMETERS = len(PARAMETERS_DATA)
TOTAL_EXAMPLES = len(EXAMPLES_DATA)
TOTAL_DEPENDENCIES = len(DEPENDENCIES_DATA)

print(f"Data loaded: {TOTAL_FUNCTIONS} functions, {TOTAL_PARAMETERS} parameters, {TOTAL_EXAMPLES} examples, {TOTAL_DEPENDENCIES} dependencies")