# UAV Flying Wing Design Data Collector
# This module contains the data definitions and collection functions for UAV flying wing designs

import json


def get_uav_flying_wing_template():
    """Return the UAV Flying Wing template metadata"""
    return {
        "part_type": "uav_flying_wing",
        "description": "Advanced UAV flying wing design with multi-section surfaces, extrusions, and loft operations",
        "domain": "Generative Shape Design",
        "complexity": "advanced",
    }


def get_uav_flying_wing_steps(template_id):
    """Return UAV Flying Wing design steps data based on actual script implementation with corrected target_object field"""
    uav_steps = [
        (
            template_id,
            1,
            "Initialize CATIA environment and enter GSD workbench",
            "Initialize CATIA application and create new part document",
            "initialization",
            "catia_objects",
            '{"workbench": "GenerativeShapeDesignWorkbench"}',
            "",
            "Initialize CAD environment",
            'catia(), documents.add("Part")',
        ),
        (
            template_id,
            2,
            "Set up hybrid shape design environment",
            "Configure hybrid shape factory and geometrical set",
            "initialization",
            "hybrid_objects",
            '{"geom_set_name": "Geometrical Set.1"}',
            "1",
            "Configure hybrid shape factory and geometrical set",
            "part.hybrid_shape_factory, hybrid_bodies.add()",
        ),
        (
            template_id,
            3,
            "Define reference planes",
            "Access origin coordinate system planes",
            "reference_setup",
            "planes",
            '{"planes": ["xy_plane", "yz_plane", "zx_plane"]}',
            "1",
            "Access origin coordinate system planes",
            "part.origin_elements",
        ),
        (
            template_id,
            4,
            "Define reference coordinate axes",
            "Create directional references for construction geometry",
            "reference_setup",
            "axes",
            '{"x_axis": [1,0,0], "y_axis": [0,1,0], "z_axis": [0,0,1]}',
            "2,3",
            "Create directional references for construction geometry",
            "hybrid_shape_factory.add_new_direction_by_coord()",
        ),
        (
            template_id,
            5,
            "Create construction plane for wing geometry",
            "Create an offset plane from the zx plane",
            "CreatePlane",
            "Plane.1",
            '{"reference_plane": "zx_plane", "offset": 500.0, "reverse": false}',
            "3",
            "Base construction plane for wing geometry",
            "hybrid_shape_factory.add_new_plane_offset()",
        ),
        (
            template_id,
            6,
            "Create root chord reference point",
            "Create a point in the middle of Plane.1",
            "CreatePoint",
            "Point.1",
            '{"plane": "Plane.1", "h_coord": -250.0, "v_coord": 0.0}',
            "5",
            "Root chord reference point",
            "hybrid_shape_factory.add_new_point_on_plane()",
        ),
        (
            template_id,
            7,
            "Create tip chord reference point",
            "Create a Point - Create a point with 300mm YZ offset from Point.1",
            "CreatePoint",
            "Point.2",
            '{"reference_plane": "Plane.1", "reference_point": "Point.1", "direction": "yz_plane", "offset": 300.0}',
            "5,6",
            "Tip chord reference point",
            "hybrid_shape_factory.add_new_point_on_surface_with_reference()",
        ),
        (
            template_id,
            8,
            "Create wing root airfoil spline",
            "Create a Spline through Point.1 and Point.2 with Z axis tangency",
            "CreateSpline",
            "Spline.1",
            '{"points": ["Point.1", "Point.2"], "tangent_point": "Point.1", "tangent_dir": "z_axis", "tension": 0.5}',
            "6,7,4",
            "First wing profile curve for root-tip transition",
            "hybrid_shape_factory.add_new_spline()",
        ),
        (
            template_id,
            9,
            "Create wing tip airfoil spline",
            "Create Spline number two (reverse direction with 0.3 tension)",
            "CreateSpline",
            "Spline.2",
            '{"points": ["Point.2", "Point.1"], "tangent_point": "Point.1", "tangent_dir": "z_axis", "tension": 0.3}',
            "6,7,4",
            "Second wing profile curve with opposite tangency",
            "hybrid_shape_factory.add_new_spline()",
        ),
        (
            template_id,
            10,
            "Create reference line for sweep direction",
            "Create a Line - Point-Direction type using Plane.1 as Direction",
            "CreateLine",
            "Line.1",
            '{"type": "Point-Direction", "point": "Point.1", "direction": "Plane.1", "start_length": 0.0, "end_length": 20.0}',
            "6,5",
            "Reference axis for construction and extrusion operations",
            "hybrid_shape_factory.add_new_line_pt_dir()",
        ),
        (
            template_id,
            11,
            "Create angled line for wing sweep control",
            "Create one more Line - Angle/Normal to curve type",
            "CreateLine",
            "Line.2",
            '{"type": "Angle/Normal", "reference_curve": "Line.1", "support_plane": "xy_plane", "point": "Point.1", "angle_deg": -30.0, "start_length": 0.0, "end_length": 20.0}',
            "10,3,6",
            "Sweep direction for wing surface extrusions",
            "hybrid_shape_factory.add_new_line_angle()",
        ),
        (
            template_id,
            12,
            "Extrude root spline to create surface scaffold",
            "Extrude Surface (1/2) - Choose Spline.1 as Profile and Line.2 as Direction",
            "ExtrudeSurface",
            "Extrude.1",
            '{"profile": "Spline.1", "direction": "Line.2", "start_length": 500.0, "end_length": 0.0}',
            "8,11",
            "First extruded wing surface section",
            "hybrid_shape_factory.add_new_extrude()",
        ),
        (
            template_id,
            13,
            "Extrude tip spline to create surface scaffold",
            "Extrude Surface (2/2) - Repeat procedure with Spline.2 as Profile",
            "ExtrudeSurface",
            "Extrude.2",
            '{"profile": "Spline.2", "direction": "Line.2", "start_length": 500.0, "end_length": 0.0}',
            "9,11",
            "Second extruded wing surface section",
            "hybrid_shape_factory.add_new_extrude()",
        ),
        (
            template_id,
            14,
            "Create additional spanwise reference points",
            "Create a Point - Create a new point as following",
            "CreatePoint",
            "Point.3",
            '{"coords": [-300, 0.0, 0.0]}',
            "",
            "Additional control points for wing extension",
            "hybrid_shape_factory.add_new_point_coord()",
        ),
        (
            template_id,
            15,
            "Create additional spanwise reference points",
            "Create a Point - Create a new point as following",
            "CreatePoint",
            "Point.4",
            '{"coords": [1000, 0.0, 0.0]}',
            "",
            "Additional control points for wing extension",
            "hybrid_shape_factory.add_new_point_coord()",
        ),
        (
            template_id,
            16,
            "Create additional spanwise splines for wing structure",
            "Create third spanwise spline - Introduce new profile curve",
            "CreateSpline",
            "Spline.3",
            '{"points": ["Point.3", "Point.4"], "tangent_point": "Point.3", "tangent_dir": "z_axis", "tension": 0.5}',
            "14,15,4",
            "Third wing profile curve",
            "hybrid_shape_factory.add_new_spline()",
        ),
        (
            template_id,
            17,
            "Create additional spanwise splines for wing structure",
            "Create fourth spanwise spline - Introduce new profile curve",
            "CreateSpline",
            "Spline.4",
            '{"points": ["Point.4", "Point.3"], "tangent_point": "Point.3", "tangent_dir": "z_axis", "tension": 0.3}',
            "14,15,4",
            "Fourth wing profile curve",
            "hybrid_shape_factory.add_new_spline()",
        ),
        (
            template_id,
            18,
            "Create guide splines for loft surface control",
            "Create a Spline connecting the two profiles with tangent directions",
            "CreateSpline",
            "Spline.5",
            '{"points": ["Point.3", "Point.1"], "tangent_Point3_dir": "y_axis", "tangent_Point1_dir": "Line.2", "tension": 1}',
            "14,6,4,11",
            "First connecting spline for loft guidance",
            "hybrid_shape_factory.add_new_spline()",
        ),
        (
            template_id,
            19,
            "Create a Spline connecting the two profiles with tangent directions",
            "Create a Spline connecting the two profiles with tangent directions",
            "CreateSpline",
            "Spline.6",
            '{"points": ["Point.4", "Point.2"], "tangent_Point4_dir": "y_axis", "tangent_Point2_dir": "y_axis", "tension": 1}',
            "15,7,4",
            "Second connecting spline for loft guidance",
            "hybrid_shape_factory.add_new_spline()",
        ),
        (
            template_id,
            20,
            "Create support extrusions for loft scaffolding",
            "Create an Extrude Surface - Extrude Spline.3 as guide surface with zx plane direction",
            "ExtrudeSurface",
            "Extrude.3",
            '{"profile": "Spline.3", "direction": "zx_plane", "start_length": -30.0, "end_length": 0.0}',
            "16,3",
            "Guide surface for loft operations",
            "hybrid_shape_factory.add_new_extrude()",
        ),
        (
            template_id,
            21,
            "Create support extrusions for loft scaffolding",
            "Create an Extrude Surface - Extrude Spline.4 as guide surface with zx plane direction",
            "ExtrudeSurface",
            "Extrude.4",
            '{"profile": "Spline.4", "direction": "zx_plane", "start_length": -30.0, "end_length": 0.0}',
            "17,3",
            "Additional guide surface for loft operations",
            "hybrid_shape_factory.add_new_extrude()",
        ),
        (
            template_id,
            22,
            "Create upper wing loft surface",
            "Create a Multi-section Surface - Choose sections and guides with tangent surfaces",
            "MultiSectionSurface",
            "Multi-sections Surface.1",
            '{"sections": ["Spline.4", "Spline.2"], "guides": ["Spline.5", "Spline.6"], "closing_points": ["Point.4", "Point.2"], "closing_faces": ["Extrude.3", "Extrude.2"]}',
            "17,9,18,19,20,13",
            "Upper wing loft surface with smooth transitions",
            "hybrid_shape_factory.add_new_loft()",
        ),
        (
            template_id,
            23,
            "Create wing surface using multi-section loft",
            "Create a Multi-section Surface - Choose sections and guides with tangent surfaces",
            "MultiSectionSurface",
            "Multi-sections Surface.2",
            '{"sections": ["Spline.3", "Spline.1"], "guides": ["Spline.5", "Spline.6"], "closing_points": ["Point.3", "Point.1"], "closing_faces": ["Extrude.4", "Extrude.1"]}',
            "16,8,18,19,21,12",
            "Lower wing loft surface with smooth transitions",
            "hybrid_shape_factory.add_new_loft()",
        ),
        (
            template_id,
            24,
            "Join extrusion surfaces",
            "Create a Join - Join Extrude.1 and Extrude.2 surfaces",
            "JoinSurfaces",
            "Join.1",
            '{"surfaces": ["Extrude.1", "Extrude.2"], "check_tangency": true, "merging_distance": 0.001}',
            "12,13",
            "Join extrusion surfaces",
            "hybrid_shape_factory.add_new_join()",
        ),
        (
            template_id,
            25,
            "Join extrusion surfaces",
            "Create a Join - Select four surfaces of the model",
            "JoinSurfaces",
            "Join.2",
            '{"surfaces": ["Multi Sections Surface.1", "Multi Sections Surface.2"], "check_tangency": true, "merging_distance": 0.001}',
            "22,23",
            "Join loft surfaces",
            "hybrid_shape_factory.add_new_join()",
        ),
        (
            template_id,
            26,
            "Join the loft surfaces together",
            "Create final unified wing surface - Unify all wing surfaces",
            "JoinSurfaces",
            "Join.3",
            '{"surfaces": ["Join.1", "Join.2"], "check_tangency": false, "check_connectivity": true, "merging_distance": 0.001}',
            "24,25",
            "Create final unified wing surface",
            "hybrid_shape_factory.add_new_join()",
        ),
        (
            template_id,
            27,
            "Add thickness to create solid wing structure",
            "Create a ThickSurface - Choose Join.1 and give thickness of 3mm",
            "ThickSurface",
            "ThickSurface.1",
            '{"surface": "Join.3", "offset1": 0, "offset2": 10.0, "offset3": 0.0}',
            "26",
            "Add thickness to create solid wing structure",
            "shape_factory.add_new_volume_thick_surface()",
        ),
        (
            template_id,
            28,
            "Mirror wing to create full wingspan",
            "Create a Symmetry - Choose ThickSurface.1 as Element and zx plane as Reference",
            "Symmetry",
            "Symmetry.1",
            '{"element": "ThickSurface.1", "reference_plane": "zx_plane", "volume_result": true}',
            "27,3",
            "Mirror wing to create full wingspan",
            "hybrid_shape_factory.add_new_symmetry()",
        ),
        (
            template_id,
            29,
            "Control element visibility for cleaner design view",
            "Hide help surfaces and set visibility for geometric elements",
            "SetVisibility",
            None,  # No new target object created - operates on existing elements
            '{"elements_to_hide": ["Plane.1", "Point.1", "Point.2", "Point.3", "Point.4", "Spline.1", "Spline.2", "Spline.3", "Spline.4", "Spline.5", "Spline.6", "Line.1", "Line.2", "Extrude.1", "Extrude.2", "Extrude.3", "Extrude.4", "Join.1", "Join.2", "Join.3", "Multi Sections Surface.1", "Multi Sections Surface.2"]}',
            "1-28",
            "Control element visibility for cleaner design view",
            "selection.add(), vis_properties.set_show()",
        ),
    ]
    return uav_steps


def get_uav_flying_wing_parameters(template_id):
    """Return UAV Flying Wing design parameters data reflecting actual script hardcoded values"""
    # Schema: (template_id, parameter_name, parameter_value, parameter_type, parameter_unit,
    #          description, min_value, max_value, is_required)
    uav_parameters = [
        (
            template_id,
            "construction_plane_offset",
            "500.0",
            "Length",
            "mm",
            "Offset distance for construction plane from ZX plane (hardcoded in step 5)",
            200.0,
            800.0,
            True,
        ),
        (
            template_id,
            "root_point_h",
            "-250.0",
            "Length",
            "mm",
            "Horizontal coordinate for root point on construction plane (hardcoded in step 6)",
            -300.0,
            -200.0,
            True,
        ),
        (
            template_id,
            "tip_offset_yz",
            "300.0",
            "Length",
            "mm",
            "YZ direction offset distance for tip point from root point (hardcoded in step 7)",
            200.0,
            400.0,
            True,
        ),
        (
            template_id,
            "spline_tension_1",
            "0.5",
            "Ratio",
            "-",
            "Tangent tension for first spline at root point (hardcoded in step 8)",
            0.1,
            1.0,
            True,
        ),
        (
            template_id,
            "spline_tension_2",
            "0.3",
            "Ratio",
            "-",
            "Tangent tension for second spline at root point (hardcoded in step 9)",
            0.1,
            1.0,
            True,
        ),
        (
            template_id,
            "line_length",
            "20.0",
            "Length",
            "mm",
            "End length parameter for reference lines (hardcoded in steps 10,11)",
            10.0,
            30.0,
            True,
        ),
        (
            template_id,
            "sweep_angle",
            "-30.0",
            "Angle",
            "deg",
            "Angle for Line.2 used in surface extrusion direction (hardcoded in step 11)",
            -45.0,
            -15.0,
            True,
        ),
        (
            template_id,
            "extrude_length",
            "500.0",
            "Length",
            "mm",
            "Extrusion length for main wing surfaces (hardcoded in steps 12,13)",
            300.0,
            700.0,
            True,
        ),
        (
            template_id,
            "point3_x",
            "-300.0",
            "Length",
            "mm",
            "X coordinate for additional Point.3 (hardcoded in step 14)",
            -400.0,
            -200.0,
            True,
        ),
        (
            template_id,
            "point4_x",
            "1000.0",
            "Length",
            "mm",
            "X coordinate for additional Point.4 (hardcoded in step 15)",
            800.0,
            1200.0,
            True,
        ),
        (
            template_id,
            "guide_extrude_length",
            "-30.0",
            "Length",
            "mm",
            "Extrusion length for guide surfaces (hardcoded in steps 20,21)",
            -50.0,
            -10.0,
            True,
        ),
        (
            template_id,
            "wing_thickness",
            "10.0",
            "Length",
            "mm",
            "Thickness offset for solid wing structure (hardcoded in step 27)",
            5.0,
            15.0,
            True,
        ),
    ]
    return uav_parameters
